"""NORA Content Meta Model — cross-domain connection catalogue (Phase 2).

[FORK] NORA exact-fidelity metamodel (noraPlanMeta.md, Phase 2).

Wires the NORA-native building blocks together with the document's §5.3.x.3
connections for the Strategic, Business, Beneficiary Experience, Data,
Applications and Security domains (the Technology §5.3.6.3 backbone already lives
in ``seed_nora_technology_relations``).

The candidates are merged **collision-safe** in ``seed.py``: any ordered
``(source, target)`` pair already defined in ``seed.RELATIONS`` (base metamodel
or the technology backbone) is skipped, preserving the one-relation-type-per-pair
rule. Only edges that add wiring for the new blocks land.

Every verb carries label + reverse_label translations for all nine non-English
locales (guarded by ``test_i18n_seed``). Shared verbs (uses / owned-by /
provided-by) are imported from the technology relation registry.
"""

from __future__ import annotations

from app.services.seed_nora_technology import _tx
from app.services.seed_nora_technology_relations import _VERBS as _TECH_VERBS


def _v(label: str, reverse: str, card: str, label_tx: dict, reverse_tx: dict) -> dict:
    return {
        "label": label,
        "reverse_label": reverse,
        "cardinality": card,
        "label_tx": label_tx,
        "reverse_tx": reverse_tx,
    }


_VERBS: dict[str, dict] = {
    "leads": _v(
        "leads",
        "is led by",
        "1:n",
        _tx(
            de="führt zu",
            fr="mène à",
            es="conduce a",
            it="guida",
            pt="conduz a",
            zh="引领",
            ru="ведёт к",
            da="fører til",
            ar="يقود إلى",
        ),
        _tx(
            de="wird geführt von",
            fr="est mené par",
            es="es conducido por",
            it="è guidato da",
            pt="é conduzido por",
            zh="由…引领",
            ru="определяется",
            da="ledes af",
            ar="مقود بواسطة",
        ),
    ),
    "translatesTo": _v(
        "translates to",
        "embodies",
        "1:n",
        _tx(
            de="übersetzt sich in",
            fr="se traduit par",
            es="se traduce en",
            it="si traduce in",
            pt="traduz-se em",
            zh="转化为",
            ru="воплощается в",
            da="omsættes til",
            ar="يُترجَم إلى",
        ),
        _tx(
            de="verkörpert",
            fr="incarne",
            es="materializa",
            it="incarna",
            pt="materializa",
            zh="体现",
            ru="воплощает",
            da="udmønter",
            ar="يجسّد",
        ),
    ),
    "belongsTo": _v(
        "belongs to",
        "comprises",
        "n:1",
        _tx(
            de="gehört zu",
            fr="appartient à",
            es="pertenece a",
            it="appartiene a",
            pt="pertence a",
            zh="属于",
            ru="относится к",
            da="hører til",
            ar="ينتمي إلى",
        ),
        _tx(
            de="umfasst",
            fr="comprend",
            es="comprende",
            it="comprende",
            pt="compreende",
            zh="包含",
            ru="включает",
            da="omfatter",
            ar="يشمل",
        ),
    ),
    "contains": _v(
        "contains",
        "is part of",
        "1:n",
        _tx(
            de="enthält",
            fr="contient",
            es="contiene",
            it="contiene",
            pt="contém",
            zh="包含",
            ru="содержит",
            da="indeholder",
            ar="يحتوي",
        ),
        _tx(
            de="ist Teil von",
            fr="fait partie de",
            es="forma parte de",
            it="fa parte di",
            pt="faz parte de",
            zh="属于",
            ru="является частью",
            da="er en del af",
            ar="جزء من",
        ),
    ),
    "achievedThrough": _v(
        "is achieved through",
        "achieves",
        "n:m",
        _tx(
            de="wird erreicht durch",
            fr="est atteint via",
            es="se logra mediante",
            it="è raggiunto tramite",
            pt="é alcançado através de",
            zh="通过…实现",
            ru="достигается через",
            da="opnås gennem",
            ar="يتحقق عبر",
        ),
        _tx(
            de="erreicht",
            fr="réalise",
            es="logra",
            it="raggiunge",
            pt="alcança",
            zh="实现",
            ru="достигает",
            da="opnår",
            ar="يحقق",
        ),
    ),
    "measuredBy": _v(
        "is measured by",
        "measures",
        "n:m",
        _tx(
            de="wird gemessen durch",
            fr="est mesuré par",
            es="es medido por",
            it="è misurato da",
            pt="é medido por",
            zh="由…衡量",
            ru="измеряется",
            da="måles af",
            ar="يُقاس بواسطة",
        ),
        _tx(
            de="misst",
            fr="mesure",
            es="mide",
            it="misura",
            pt="mede",
            zh="衡量",
            ru="измеряет",
            da="måler",
            ar="يقيس",
        ),
    ),
    "implementedThrough": _v(
        "is implemented through",
        "implements",
        "n:m",
        _tx(
            de="wird umgesetzt durch",
            fr="est mis en œuvre via",
            es="se implementa mediante",
            it="è implementato tramite",
            pt="é implementado através de",
            zh="通过…实现",
            ru="реализуется через",
            da="implementeres gennem",
            ar="يُنفَّذ عبر",
        ),
        _tx(
            de="setzt um",
            fr="met en œuvre",
            es="implementa",
            it="implementa",
            pt="implementa",
            zh="实现",
            ru="реализует",
            da="implementerer",
            ar="ينفّذ",
        ),
    ),
    "entersContractsWith": _v(
        "enters into contracts with",
        "is contracted by",
        "n:m",
        _tx(
            de="schließt Verträge mit",
            fr="conclut des contrats avec",
            es="celebra contratos con",
            it="stipula contratti con",
            pt="celebra contratos com",
            zh="与…签订合同",
            ru="заключает договоры с",
            da="indgår kontrakter med",
            ar="يتعاقد مع",
        ),
        _tx(
            de="ist beauftragt von",
            fr="est engagé par",
            es="es contratado por",
            it="è ingaggiato da",
            pt="é contratado por",
            zh="受…签约",
            ru="привлекается",
            da="er kontraheret af",
            ar="متعاقَد معه من",
        ),
    ),
    "providedTo": _v(
        "is provided to",
        "receives",
        "n:m",
        _tx(
            de="wird bereitgestellt für",
            fr="est fourni à",
            es="se proporciona a",
            it="è fornito a",
            pt="é fornecido a",
            zh="提供给",
            ru="предоставляется",
            da="leveres til",
            ar="يُقدَّم إلى",
        ),
        _tx(
            de="erhält",
            fr="reçoit",
            es="recibe",
            it="riceve",
            pt="recebe",
            zh="接收",
            ru="получает",
            da="modtager",
            ar="يستلم",
        ),
    ),
    "providedThrough": _v(
        "is provided through",
        "delivers",
        "n:m",
        _tx(
            de="wird bereitgestellt durch",
            fr="est fourni via",
            es="se presta a través de",
            it="è fornito tramite",
            pt="é fornecido através de",
            zh="通过…提供",
            ru="предоставляется через",
            da="leveres gennem",
            ar="يُقدَّم عبر",
        ),
        _tx(
            de="liefert",
            fr="fournit",
            es="entrega",
            it="eroga",
            pt="entrega",
            zh="交付",
            ru="доставляет",
            da="leverer",
            ar="يقدّم",
        ),
    ),
    "produces": _v(
        "produces",
        "is produced by",
        "1:n",
        _tx(
            de="erzeugt",
            fr="produit",
            es="produce",
            it="produce",
            pt="produz",
            zh="产出",
            ru="производит",
            da="producerer",
            ar="ينتج",
        ),
        _tx(
            de="wird erzeugt von",
            fr="est produit par",
            es="es producido por",
            it="è prodotto da",
            pt="é produzido por",
            zh="由…产出",
            ru="производится",
            da="produceres af",
            ar="يُنتَج بواسطة",
        ),
    ),
    "executedBy": _v(
        "is executed by",
        "executes",
        "n:m",
        _tx(
            de="wird ausgeführt von",
            fr="est exécuté par",
            es="es ejecutado por",
            it="è eseguito da",
            pt="é executado por",
            zh="由…执行",
            ru="выполняется",
            da="udføres af",
            ar="يُنفَّذ بواسطة",
        ),
        _tx(
            de="führt aus",
            fr="exécute",
            es="ejecuta",
            it="esegue",
            pt="executa",
            zh="执行",
            ru="выполняет",
            da="udfører",
            ar="ينفّذ",
        ),
    ),
    "governedThrough": _v(
        "is governed through",
        "governs",
        "n:m",
        _tx(
            de="wird geregelt durch",
            fr="est régi par",
            es="se rige por",
            it="è governato da",
            pt="é regido por",
            zh="受…治理",
            ru="регулируется",
            da="styres gennem",
            ar="يُحكَم عبر",
        ),
        _tx(
            de="regelt",
            fr="régit",
            es="rige",
            it="governa",
            pt="rege",
            zh="治理",
            ru="регулирует",
            da="styrer",
            ar="يحكم",
        ),
    ),
    "executes": _v(
        "performs",
        "is performed by",
        "n:m",
        _tx(
            de="übt aus",
            fr="assure",
            es="desempeña",
            it="svolge",
            pt="desempenha",
            zh="担任",
            ru="выполняет",
            da="udøver",
            ar="يؤدي",
        ),
        _tx(
            de="wird ausgeübt von",
            fr="est assuré par",
            es="es desempeñado por",
            it="è svolto da",
            pt="é desempenhado por",
            zh="由…担任",
            ru="выполняется",
            da="udøves af",
            ar="يُؤدى بواسطة",
        ),
    ),
    "responsibleFor": _v(
        "is responsible for",
        "is under responsibility of",
        "n:m",
        _tx(
            de="ist verantwortlich für",
            fr="est responsable de",
            es="es responsable de",
            it="è responsabile di",
            pt="é responsável por",
            zh="负责",
            ru="отвечает за",
            da="er ansvarlig for",
            ar="مسؤول عن",
        ),
        _tx(
            de="unterliegt der Verantwortung von",
            fr="relève de la responsabilité de",
            es="está bajo la responsabilidad de",
            it="è sotto la responsabilità di",
            pt="está sob a responsabilidade de",
            zh="归…负责",
            ru="находится в ведении",
            da="er under ansvar af",
            ar="تحت مسؤولية",
        ),
    ),
    "appliesTo": _v(
        "applies to",
        "is governed by",
        "n:m",
        _tx(
            de="gilt für",
            fr="s'applique à",
            es="se aplica a",
            it="si applica a",
            pt="aplica-se a",
            zh="适用于",
            ru="применяется к",
            da="gælder for",
            ar="ينطبق على",
        ),
        _tx(
            de="wird geregelt durch",
            fr="est régi par",
            es="es regido por",
            it="è regolato da",
            pt="é regido por",
            zh="受…约束",
            ru="регулируется",
            da="reguleres af",
            ar="محكوم بـ",
        ),
    ),
    "benefitsFrom": _v(
        "benefits from",
        "benefits",
        "n:m",
        _tx(
            de="profitiert von",
            fr="bénéficie de",
            es="se beneficia de",
            it="beneficia di",
            pt="beneficia de",
            zh="受益于",
            ru="получает выгоду от",
            da="drager fordel af",
            ar="يستفيد من",
        ),
        _tx(
            de="kommt zugute",
            fr="profite à",
            es="beneficia a",
            it="beneficia",
            pt="beneficia",
            zh="惠及",
            ru="приносит пользу",
            da="gavner",
            ar="يفيد",
        ),
    ),
    "interactsWith": _v(
        "interacts with",
        "interacts with",
        "n:m",
        _tx(
            de="interagiert mit",
            fr="interagit avec",
            es="interactúa con",
            it="interagisce con",
            pt="interage com",
            zh="与…交互",
            ru="взаимодействует с",
            da="interagerer med",
            ar="يتفاعل مع",
        ),
        _tx(
            de="interagiert mit",
            fr="interagit avec",
            es="interactúa con",
            it="interagisce con",
            pt="interage com",
            zh="与…交互",
            ru="взаимодействует с",
            da="interagerer med",
            ar="يتفاعل مع",
        ),
    ),
    "represents": _v(
        "represents",
        "is represented by",
        "1:n",
        _tx(
            de="repräsentiert",
            fr="représente",
            es="representa",
            it="rappresenta",
            pt="representa",
            zh="代表",
            ru="представляет",
            da="repræsenterer",
            ar="يمثّل",
        ),
        _tx(
            de="wird repräsentiert von",
            fr="est représenté par",
            es="es representado por",
            it="è rappresentato da",
            pt="é representado por",
            zh="被…代表",
            ru="представлен",
            da="repræsenteres af",
            ar="مُمثَّل بواسطة",
        ),
    ),
    "constitutes": _v(
        "constitutes",
        "is constituted by",
        "n:1",
        _tx(
            de="bildet",
            fr="constitue",
            es="constituye",
            it="costituisce",
            pt="constitui",
            zh="构成",
            ru="образует",
            da="udgør",
            ar="يُشكّل",
        ),
        _tx(
            de="wird gebildet aus",
            fr="est constitué de",
            es="está constituido por",
            it="è costituito da",
            pt="é constituído por",
            zh="由…构成",
            ru="состоит из",
            da="er udgjort af",
            ar="مُكوَّن من",
        ),
    ),
    "describedThrough": _v(
        "is described through",
        "describes",
        "1:n",
        _tx(
            de="wird beschrieben durch",
            fr="est décrit par",
            es="se describe mediante",
            it="è descritto da",
            pt="é descrito por",
            zh="通过…描述",
            ru="описывается",
            da="beskrives gennem",
            ar="يُوصَف عبر",
        ),
        _tx(
            de="beschreibt",
            fr="décrit",
            es="describe",
            it="descrive",
            pt="descreve",
            zh="描述",
            ru="описывает",
            da="beskriver",
            ar="يصف",
        ),
    ),
    "storedIn": _v(
        "is stored in",
        "stores",
        "n:1",
        _tx(
            de="wird gespeichert in",
            fr="est stocké dans",
            es="se almacena en",
            it="è archiviato in",
            pt="é armazenado em",
            zh="存储于",
            ru="хранится в",
            da="lagres i",
            ar="مُخزَّن في",
        ),
        _tx(
            de="speichert",
            fr="stocke",
            es="almacena",
            it="archivia",
            pt="armazena",
            zh="存储",
            ru="хранит",
            da="lagrer",
            ar="يخزّن",
        ),
    ),
    "linkedTo": _v(
        "is linked to",
        "is linked from",
        "n:m",
        _tx(
            de="ist verknüpft mit",
            fr="est lié à",
            es="está vinculado a",
            it="è collegato a",
            pt="está ligado a",
            zh="关联到",
            ru="связан с",
            da="er knyttet til",
            ar="مرتبط بـ",
        ),
        _tx(
            de="ist verknüpft von",
            fr="est lié depuis",
            es="está vinculado desde",
            it="è collegato da",
            pt="está ligado a partir de",
            zh="被…关联",
            ru="связан с",
            da="er knyttet fra",
            ar="مرتبط من",
        ),
    ),
    "usedIn": _v(
        "is used in",
        "uses",
        "n:m",
        _tx(
            de="wird verwendet in",
            fr="est utilisé dans",
            es="se usa en",
            it="è usato in",
            pt="é usado em",
            zh="用于",
            ru="используется в",
            da="bruges i",
            ar="يُستخدَم في",
        ),
        _tx(
            de="verwendet",
            fr="utilise",
            es="usa",
            it="usa",
            pt="usa",
            zh="使用",
            ru="использует",
            da="bruger",
            ar="يستخدم",
        ),
    ),
    "serves": _v(
        "serves",
        "is served by",
        "n:m",
        _tx(
            de="bedient",
            fr="dessert",
            es="sirve a",
            it="serve",
            pt="serve",
            zh="服务于",
            ru="обслуживает",
            da="betjener",
            ar="يخدم",
        ),
        _tx(
            de="wird bedient von",
            fr="est desservi par",
            es="es servido por",
            it="è servito da",
            pt="é servido por",
            zh="由…服务",
            ru="обслуживается",
            da="betjenes af",
            ar="يُخدَم بواسطة",
        ),
    ),
    "managedBy": _v(
        "is managed by",
        "manages",
        "n:1",
        _tx(
            de="wird verwaltet von",
            fr="est géré par",
            es="es gestionado por",
            it="è gestito da",
            pt="é gerido por",
            zh="由…管理",
            ru="управляется",
            da="administreres af",
            ar="يُدار بواسطة",
        ),
        _tx(
            de="verwaltet",
            fr="gère",
            es="gestiona",
            it="gestisce",
            pt="gere",
            zh="管理",
            ru="управляет",
            da="administrerer",
            ar="يدير",
        ),
    ),
    "automates": _v(
        "automates",
        "is automated by",
        "n:m",
        _tx(
            de="automatisiert",
            fr="automatise",
            es="automatiza",
            it="automatizza",
            pt="automatiza",
            zh="自动化",
            ru="автоматизирует",
            da="automatiserer",
            ar="يؤتمت",
        ),
        _tx(
            de="wird automatisiert von",
            fr="est automatisé par",
            es="es automatizado por",
            it="è automatizzato da",
            pt="é automatizado por",
            zh="由…自动化",
            ru="автоматизируется",
            da="automatiseres af",
            ar="يُؤتمت بواسطة",
        ),
    ),
    "handles": _v(
        "handles",
        "is handled by",
        "n:m",
        _tx(
            de="verarbeitet",
            fr="traite",
            es="maneja",
            it="gestisce",
            pt="processa",
            zh="处理",
            ru="обрабатывает",
            da="håndterer",
            ar="يعالج",
        ),
        _tx(
            de="wird verarbeitet von",
            fr="est traité par",
            es="es manejado por",
            it="è gestito da",
            pt="é processado por",
            zh="由…处理",
            ru="обрабатывается",
            da="håndteres af",
            ar="يُعالَج بواسطة",
        ),
    ),
    "exposes": _v(
        "exposes",
        "is exposed by",
        "1:n",
        _tx(
            de="stellt bereit",
            fr="expose",
            es="expone",
            it="espone",
            pt="expõe",
            zh="暴露",
            ru="предоставляет",
            da="eksponerer",
            ar="يوفّر",
        ),
        _tx(
            de="wird bereitgestellt von",
            fr="est exposé par",
            es="es expuesto por",
            it="è esposto da",
            pt="é exposto por",
            zh="由…暴露",
            ru="предоставляется",
            da="eksponeres af",
            ar="مُوفَّر بواسطة",
        ),
    ),
    "consumedBy": _v(
        "is consumed by",
        "consumes",
        "n:m",
        _tx(
            de="wird konsumiert von",
            fr="est consommé par",
            es="es consumido por",
            it="è consumato da",
            pt="é consumido por",
            zh="被…消费",
            ru="потребляется",
            da="forbruges af",
            ar="يُستهلَك بواسطة",
        ),
        _tx(
            de="konsumiert",
            fr="consomme",
            es="consume",
            it="consuma",
            pt="consome",
            zh="消费",
            ru="потребляет",
            da="forbruger",
            ar="يستهلك",
        ),
    ),
    "deliveredThrough": _v(
        "is delivered through",
        "exchanges",
        "n:m",
        _tx(
            de="wird geliefert über",
            fr="est livré via",
            es="se entrega a través de",
            it="è consegnato tramite",
            pt="é entregue através de",
            zh="通过…交付",
            ru="доставляется через",
            da="leveres gennem",
            ar="يُسلَّم عبر",
        ),
        _tx(
            de="tauscht aus",
            fr="échange",
            es="intercambia",
            it="scambia",
            pt="troca",
            zh="交换",
            ru="обменивает",
            da="udveksler",
            ar="يتبادل",
        ),
    ),
    "securedThrough": _v(
        "is secured through",
        "secures",
        "n:m",
        _tx(
            de="wird gesichert durch",
            fr="est sécurisé par",
            es="está protegido por",
            it="è protetto da",
            pt="é protegido por",
            zh="通过…保护",
            ru="защищается",
            da="sikres gennem",
            ar="مؤمَّن عبر",
        ),
        _tx(
            de="sichert",
            fr="sécurise",
            es="protege",
            it="protegge",
            pt="protege",
            zh="保护",
            ru="защищает",
            da="sikrer",
            ar="يؤمّن",
        ),
    ),
}

# Shared verbs from the technology registry (uses / owned-by / provided-by).
for _name in ("uses", "ownedBy", "providedBy"):
    _VERBS.setdefault(_name, _TECH_VERBS[_name])

# ---------------------------------------------------------------------------
# (verb, source, target) — the document's §5.3.x.3 connections for the new
# building blocks. Reverse-duplicate pairs are omitted; any pair already in the
# base seed is skipped at merge time in seed.py.
# ---------------------------------------------------------------------------

_TRIPLES: list[tuple[str, str, str]] = [
    # Strategic Alignment (§5.3.1.3)
    ("leads", "Vision", "Mission"),
    ("ownedBy", "Vision", "OrganizationalUnit"),
    ("translatesTo", "Mission", "Objective"),
    ("belongsTo", "Objective", "Pillar"),
    ("achievedThrough", "Objective", "Initiative"),
    ("contains", "Pillar", "Initiative"),
    ("contains", "Pillar", "Objective"),
    ("contains", "Initiative", "Project"),
    ("ownedBy", "Project", "OrganizationalUnit"),
    ("providedBy", "Project", "ServiceProvider"),
    # NB: KPI "measured-by" edges (Objective/Initiative/Project/GovService/
    # BusinessProcess → KPI, KPI → OrganizationalUnit) are intentionally NOT here:
    # KPI is defined in nora_profile (not seed.TYPES), so its relations belong
    # alongside its type definition. Tracked as a Phase 2 follow-up.
    # Business Architecture (§5.3.2.3)
    ("achievedThrough", "BusinessCapability", "OrganizationalUnit"),
    ("implementedThrough", "BusinessCapability", "ProcessesGroup"),
    ("entersContractsWith", "OrganizationalUnit", "ServiceProvider"),
    ("belongsTo", "Position", "OrganizationalUnit"),
    ("ownedBy", "GovService", "OrganizationalUnit"),
    ("providedTo", "GovService", "Beneficiary"),
    ("providedBy", "GovService", "ServiceProvider"),
    ("uses", "GovService", "ModelTemplate"),
    ("produces", "GovService", "Product"),
    ("contains", "ProcessesGroup", "BusinessProcess"),
    ("executedBy", "ProcessesGroup", "Position"),
    ("achievedThrough", "ProcessesGroup", "BusinessCapability"),
    ("belongsTo", "BusinessProcess", "ProcessesGroup"),
    ("uses", "BusinessProcess", "ModelTemplate"),
    ("executedBy", "BusinessProcess", "Role"),
    ("governedThrough", "BusinessProcess", "Policy"),
    ("produces", "BusinessProcess", "Product"),
    ("providedThrough", "BusinessProcess", "Activity"),
    ("belongsTo", "Activity", "BusinessProcess"),
    ("executedBy", "Activity", "Role"),
    ("governedThrough", "Activity", "Policy"),
    ("providedTo", "Product", "Beneficiary"),
    ("providedThrough", "Product", "Application"),
    ("ownedBy", "Product", "OrganizationalUnit"),
    ("executes", "Position", "Role"),
    ("responsibleFor", "Role", "DataObject"),
    ("appliesTo", "Policy", "DataObject"),
    ("uses", "ModelTemplate", "DataObject"),
    # Beneficiary Experience (§5.3.3.3)
    ("benefitsFrom", "Beneficiary", "GovService"),
    ("interactsWith", "Beneficiary", "ServiceProvider"),
    ("interactsWith", "Beneficiary", "OrganizationalUnit"),
    ("represents", "Persona", "Beneficiary"),
    ("contains", "BeneficiaryJourney", "Phase"),
    ("belongsTo", "BeneficiaryJourney", "Persona"),
    ("belongsTo", "Step", "Phase"),
    ("constitutes", "Phase", "BeneficiaryJourney"),
    # Data Architecture (§5.3.4.3)
    ("describedThrough", "DataObject", "DataAttribute"),
    ("storedIn", "DataObject", "DataVault"),
    ("linkedTo", "DataObject", "BusinessCapability"),
    ("ownedBy", "DataObject", "OrganizationalUnit"),
    ("usedIn", "DataObject", "Application"),
    ("securedThrough", "DataVault", "SecurityHardware"),
    ("securedThrough", "DataVault", "SecuritySoftware"),
    ("securedThrough", "DataVault", "SecurityService"),
    # Applications Architecture (§5.3.5.3)
    ("contains", "Application", "ApplicationModule"),
    ("exposes", "Application", "Interface"),
    ("serves", "Application", "Beneficiary"),
    ("managedBy", "Application", "Role"),
    ("ownedBy", "Application", "OrganizationalUnit"),
    ("automates", "Application", "BusinessProcess"),
    ("handles", "Application", "DataObject"),
    ("securedThrough", "Application", "SecurityHardware"),
    ("securedThrough", "Application", "SecuritySoftware"),
    ("securedThrough", "Application", "SecurityService"),
    ("contains", "ApplicationModule", "ApplicationFunction"),
    ("exposes", "ApplicationFunction", "Interface"),
    ("consumedBy", "Interface", "Application"),
    ("deliveredThrough", "Interface", "DataObject"),
    ("securedThrough", "Interface", "SecurityHardware"),
    ("securedThrough", "Interface", "SecuritySoftware"),
    ("securedThrough", "Interface", "SecurityService"),
    # Security Architecture (§5.3.7.3) — server hardening
    ("securedThrough", "Server", "SecurityHardware"),
    ("securedThrough", "Server", "SecuritySoftware"),
    ("securedThrough", "Server", "SecurityService"),
]


NORA_DOMAIN_RELATIONS: list[dict] = []
_seen_pairs: set[tuple[str, str]] = set()
for _i, (_verb, _src, _tgt) in enumerate(_TRIPLES):
    if _src == _tgt or (_src, _tgt) in _seen_pairs:
        continue
    _seen_pairs.add((_src, _tgt))
    _spec = _VERBS[_verb]
    NORA_DOMAIN_RELATIONS.append(
        {
            "key": f"relNora2{_src}{_tgt}",
            "label": _spec["label"],
            "reverse_label": _spec["reverse_label"],
            "source_type_key": _src,
            "target_type_key": _tgt,
            "cardinality": _spec["cardinality"],
            "sort_order": 700 + _i,
            "translations": {
                "label": _spec["label_tx"],
                "reverse_label": _spec["reverse_tx"],
            },
        }
    )
