"""Seed all 67 NORA/DGA EA Viewpoints into viewpoint_definitions table."""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.viewpoint_definition import ViewpointDefinition

# All 67 NORA viewpoints from The EA Viewpoints Document v2.0 (Dec 2024)
# Organized by domain, level, and type
NORA_VIEWPOINTS = [
    # Strategic Alignment (3)
    {
        "code": "SA_OBJ_LIST",
        "name_en": "Strategic Objectives catalog",
        "name_ar": "كتالوج الأهداف الاستراتيجية",
        "domain": "strategic_alignment",
        "level": "conceptual",
        "type": "list",
        "description_en": "List of strategic objectives with code, pillar, owner, KPI and current/target values",
        "description_ar": "قائمة الأهداف الاستراتيجية مع الرمز والركيزة والمالك والمؤشرات",
        "building_blocks": ["Objective"],
        "target_route": "/inventory?type=Objective",
        "status": "available",
        "sort_order": 1,
    },
    {
        "code": "SA_OBJ_PILLAR_MTX",
        "name_en": "Objectives/Pillars",
        "name_ar": "الأهداف / الركائز",
        "domain": "strategic_alignment",
        "level": "conceptual",
        "type": "matrix",
        "description_en": "Matrix showing intersections between strategic objectives and pillars",
        "description_ar": "مصفوفة تظهر التقاطعات بين الأهداف الاستراتيجية والركائز",
        "building_blocks": ["Objective", "Pillar"],
        "target_route": "/reports/matrix?source=Objective&target=Pillar",
        "status": "available",
        "sort_order": 2,
    },
    {
        "code": "SA_STRATEGIC_HOUSE",
        "name_en": "Strategic House",
        "name_ar": "البيت الاستراتيجي",
        "domain": "strategic_alignment",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram summarizing strategy including vision, mission, pillars, objectives, and KPIs",
        "description_ar": "رسم توضيحي للاستراتيجية يتضمن الرؤية والرسالة والركائز والأهداف والمؤشرات",
        "building_blocks": ["Vision", "Mission", "Objective", "Pillar", "KPI"],
        "target_route": "/reports/strategic-house-nora",
        "status": "available",
        "sort_order": 3,
    },
    # Business (14)
    {
        "code": "BIZ_SVC_LIST",
        "name_en": "Service catalog",
        "name_ar": "كتالوج الخدمات",
        "domain": "business",
        "level": "conceptual",
        "type": "list",
        "description_en": "List of government services with code, name, description, and organization",
        "description_ar": "قائمة الخدمات الحكومية مع الرمز والاسم والوصف والمنظمة",
        "building_blocks": ["GovService"],
        "target_route": "/inventory?type=GovService",
        "status": "available",
        "sort_order": 4,
    },
    {
        "code": "BIZ_ORG_STRUCTURE",
        "name_en": "Organizational Structure",
        "name_ar": "الهيكل التنظيمي",
        "domain": "business",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram of organizational hierarchy and reporting lines",
        "description_ar": "رسم توضيحي للهيكل التنظيمي وخطوط التقارير",
        "building_blocks": ["Organization"],
        "target_route": "/inventory?type=Organization",
        "status": "available",
        "sort_order": 5,
    },
    {
        "code": "BIZ_VALUE_CHAIN",
        "name_en": "Business Value Chain",
        "name_ar": "سلسلة القيمة",
        "domain": "business",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing value chain with capabilities, services, and processes",
        "description_ar": "رسم توضيحي لسلسلة القيمة مع القدرات والخدمات والعمليات",
        "building_blocks": ["BusinessCapability", "GovService", "BusinessProcess"],
        "target_route": "/value-stream-catalogue",
        "status": "partial",
        "sort_order": 6,
    },
    {
        "code": "BIZ_PROC_LIST",
        "name_en": "Business Processes Catalog",
        "name_ar": "كتالوج العمليات الحكومية",
        "domain": "business",
        "level": "logical",
        "type": "list",
        "description_en": "List of business processes with owner, service, capability, automation level, and status",
        "description_ar": "قائمة العمليات الحكومية مع المالك والخدمة والقدرة ومستوى الأتمتة والحالة",
        "building_blocks": ["BusinessProcess"],
        "target_route": "/inventory?type=BusinessProcess",
        "status": "available",
        "sort_order": 7,
    },
    {
        "code": "BIZ_TEMPLATE_LIST",
        "name_en": "Model/Template Catalog",
        "name_ar": "كتالوج النماذج والقوالب",
        "domain": "business",
        "level": "logical",
        "type": "list",
        "description_en": "List of business models and templates used by services and processes",
        "description_ar": "قائمة نماذج وقوالب الأعمال المستخدمة من قبل الخدمات والعمليات",
        "building_blocks": ["ModelTemplate"],
        "target_route": "/inventory?type=ModelTemplate",
        "status": "available",
        "sort_order": 8,
    },
    {
        "code": "BIZ_POLICY_LIST",
        "name_en": "Policy Catalog",
        "name_ar": "كتالوج السياسات",
        "domain": "business",
        "level": "logical",
        "type": "list",
        "description_en": "List of business policies governing services and processes",
        "description_ar": "قائمة السياسات الحكومية التي تحكم الخدمات والعمليات",
        "building_blocks": ["Policy"],
        "target_route": "/grc?tab=governance",
        "status": "partial",
        "sort_order": 9,
    },
    {
        "code": "BIZ_ORG_SVC_MTX",
        "name_en": "Organizational Units/Services",
        "name_ar": "الوحدات التنظيمية / الخدمات",
        "domain": "business",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing which services are provided by each organizational unit",
        "description_ar": "مصفوفة توضح الخدمات التي تقدمها كل وحدة تنظيمية",
        "building_blocks": ["Organization", "GovService"],
        "target_route": "/reports/matrix?source=Organization&target=GovService",
        "status": "missing",
        "sort_order": 10,
    },
    {
        "code": "BIZ_CAP_ORG_MTX",
        "name_en": "Business Capabilities/Organizational Units",
        "name_ar": "القدرات الحكومية / الوحدات التنظيمية",
        "domain": "business",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing capabilities delivered by organizational units",
        "description_ar": "مصفوفة توضح القدرات التي تقدمها الوحدات التنظيمية",
        "building_blocks": ["BusinessCapability", "Organization"],
        "target_route": "/reports/matrix?source=BusinessCapability&target=Organization",
        "status": "available",
        "sort_order": 11,
    },
    {
        "code": "BIZ_INTERACTION_DIAG",
        "name_en": "Interaction Model for the Entity / Organizational Unit",
        "name_ar": "نموذج التفاعل للمنظمة / الوحدة التنظيمية",
        "domain": "business",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing interactions between an entity and external/internal stakeholders",
        "description_ar": "رسم توضيحي للتفاعلات بين المنظمة والجهات الداخلية والخارجية",
        "building_blocks": ["Organization"],
        "target_route": "/reports/dependencies?type=Organization",
        "status": "partial",
        "sort_order": 12,
    },
    {
        "code": "BIZ_MANDATE_POS_MTX",
        "name_en": "Mandates/Positions",
        "name_ar": "الصلاحيات / المناصب",
        "domain": "business",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing mandates assigned to each position in organizational units",
        "description_ar": "مصفوفة توضح الصلاحيات المخصصة لكل منصب في الوحدات التنظيمية",
        "building_blocks": ["Mandate", "Position", "Organization"],
        "target_route": "/reports/matrix?source=Position&target=Mandate",
        "status": "available",
        "sort_order": 13,
    },
    {
        "code": "BIZ_SVC_TEMPLATE_MTX",
        "name_en": "Services/Models",
        "name_ar": "الخدمات / النماذج",
        "domain": "business",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing relationship between services and their supporting models/templates",
        "description_ar": "مصفوفة توضح العلاقة بين الخدمات والنماذج التي تدعمها",
        "building_blocks": ["GovService", "ModelTemplate"],
        "target_route": "/reports/matrix?source=GovService&target=ModelTemplate",
        "status": "missing",
        "sort_order": 14,
    },
    {
        "code": "BIZ_SVC_PROC_MTX",
        "name_en": "Services/Business Processes",
        "name_ar": "الخدمات / العمليات الحكومية",
        "domain": "business",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing which processes execute each service",
        "description_ar": "مصفوفة توضح العمليات التي تنفذ كل خدمة",
        "building_blocks": ["GovService", "BusinessProcess"],
        "target_route": "/reports/matrix?source=GovService&target=BusinessProcess",
        "status": "missing",
        "sort_order": 15,
    },
    {
        "code": "BIZ_SVC_APP_MTX",
        "name_en": "Services/Applications",
        "name_ar": "الخدمات / التطبيقات",
        "domain": "business",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing which applications support each service",
        "description_ar": "مصفوفة توضح التطبيقات التي تدعم كل خدمة",
        "building_blocks": ["GovService", "Application"],
        "target_route": "/reports/matrix?source=GovService&target=Application",
        "status": "missing",
        "sort_order": 16,
    },
    {
        "code": "BIZ_PROC_DIAG",
        "name_en": "Business Process Diagram",
        "name_ar": "رسم تخطيطي للعملية الحكومية",
        "domain": "business",
        "level": "physical",
        "type": "diagram",
        "description_en": "Full BPMN 2.0 diagram of a business process with versioning and approval workflow",
        "description_ar": "رسم توضيحي BPMN 2.0 للعملية الحكومية مع إدارة الإصدارات والموافقة",
        "building_blocks": ["BusinessProcess"],
        "target_route": "/bpm",
        "status": "available",
        "sort_order": 17,
    },
    # Beneficiary Experience (8)
    {
        "code": "BEN_PERSONA_CARD",
        "name_en": "Beneficiary Persona Card",
        "name_ar": "بطاقة شخصية المستفيد",
        "domain": "beneficiary_experience",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Card showing a beneficiary persona with demographics, needs, goals, and pain points",
        "description_ar": "بطاقة توضح شخصية المستفيد مع المعلومات الديموغرافية والاحتياجات والأهداف والتحديات",
        "building_blocks": ["BeneficiaryPersona"],
        "target_route": "/inventory?type=BeneficiaryPersona",
        "status": "missing",
        "sort_order": 18,
    },
    {
        "code": "BEN_JOURNEY_IMPROVE_LIST",
        "name_en": "List of Improvements to Beneficiary Journeys",
        "name_ar": "قائمة تحسينات رحلات المستفيد",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "list",
        "description_en": "List of proposed improvements to beneficiary journeys with impact and effort",
        "description_ar": "قائمة بالتحسينات المقترحة لرحلات المستفيد مع التأثير والجهد",
        "building_blocks": ["JourneyImprovement"],
        "target_route": "/inventory?type=JourneyImprovement",
        "status": "available",
        "sort_order": 19,
    },
    {
        "code": "BEN_BENEF_PERSONA_MTX",
        "name_en": "Beneficiaries/Beneficiary Personas",
        "name_ar": "المستفيدون / شخصيات المستفيدين",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing beneficiary segments and their associated personas",
        "description_ar": "مصفوفة توضح شرائح المستفيدين والشخصيات المرتبطة بها",
        "building_blocks": ["Beneficiary", "BeneficiaryPersona"],
        "target_route": "/reports/matrix?source=Beneficiary&target=BeneficiaryPersona",
        "status": "missing",
        "sort_order": 20,
    },
    {
        "code": "BEN_SVC_PERSONA_MTX",
        "name_en": "Services/Beneficiary Personas",
        "name_ar": "الخدمات / شخصيات المستفيدين",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing which services are used by each beneficiary persona",
        "description_ar": "مصفوفة توضح الخدمات التي يستخدمها كل شخصية مستفيد",
        "building_blocks": ["GovService", "BeneficiaryPersona"],
        "target_route": "/reports/matrix?source=GovService&target=BeneficiaryPersona",
        "status": "missing",
        "sort_order": 21,
    },
    {
        "code": "BEN_SVC_JOURNEY_MTX",
        "name_en": "Services/Beneficiary Journeys",
        "name_ar": "الخدمات / رحلات المستفيد",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing which journeys involve each service",
        "description_ar": "مصفوفة توضح الرحلات التي تتضمن كل خدمة",
        "building_blocks": ["GovService", "BeneficiaryJourney"],
        "target_route": "/reports/matrix?source=GovService&target=BeneficiaryJourney",
        "status": "missing",
        "sort_order": 22,
    },
    {
        "code": "BEN_PERSONA_JOURNEY_MTX",
        "name_en": "Beneficiary Personas/Beneficiary Journeys",
        "name_ar": "شخصيات المستفيدين / رحلات المستفيد",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing which journeys each persona experiences",
        "description_ar": "مصفوفة توضح الرحلات التي تمر بها كل شخصية",
        "building_blocks": ["BeneficiaryPersona", "BeneficiaryJourney"],
        "target_route": "/reports/matrix?source=BeneficiaryPersona&target=BeneficiaryJourney",
        "status": "missing",
        "sort_order": 23,
    },
    {
        "code": "BEN_JOURNEY_MAP",
        "name_en": "Beneficiary Journey Map",
        "name_ar": "خريطة رحلة المستفيد",
        "domain": "beneficiary_experience",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing beneficiary journey stages, touchpoints, pain points, and channels",
        "description_ar": "رسم توضيحي لمراحل رحلة المستفيد والنقاط التفاعلية والتحديات والقنوات",
        "building_blocks": ["BeneficiaryJourney"],
        "target_route": "/reports/journey-map-nora",
        "status": "available",
        "sort_order": 24,
    },
    {
        "code": "BEN_JOURNEY_PRIORITY_MTX",
        "name_en": "Beneficiary Journeys / Experience Improvement Priorities",
        "name_ar": "رحلات المستفيد / أولويات تحسين التجربة",
        "domain": "beneficiary_experience",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing journey improvement priorities with scores and owners",
        "description_ar": "مصفوفة توضح أولويات تحسين الرحلة مع الدرجات والمالكين",
        "building_blocks": ["BeneficiaryJourney", "JourneyImprovement"],
        "target_route": "/reports/matrix?source=BeneficiaryJourney&target=JourneyImprovement",
        "status": "missing",
        "sort_order": 25,
    },
    # Data (8)
    {
        "code": "DAT_ENTITIES_LAND",
        "name_en": "Data Entities Landscape",
        "name_ar": "منظر كيانات البيانات",
        "domain": "data",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing data domains, entities, ownership, and application usage",
        "description_ar": "رسم توضيحي يظهر مجالات البيانات والكيانات والملكية والاستخدام",
        "building_blocks": ["DataObject"],
        "target_route": "/reports/dependencies?type=DataObject",
        "status": "partial",
        "sort_order": 26,
    },
    {
        "code": "DAT_OWNER_LIST",
        "name_en": "List of Data Owners",
        "name_ar": "قائمة مالكي البيانات",
        "domain": "data",
        "level": "logical",
        "type": "list",
        "description_en": "List of data owners and stewards with responsibilities and organization",
        "description_ar": "قائمة مالكي البيانات والقائمين عليها مع المسؤوليات والمنظمة",
        "building_blocks": ["DataObject"],
        "target_route": "/inventory?type=DataObject&role=Data%20Owner",
        "status": "partial",
        "sort_order": 27,
    },
    {
        "code": "DAT_ENTITY_CAP_MTX",
        "name_en": "Data Entity/Business Capability",
        "name_ar": "كيان البيانات / القدرة الحكومية",
        "domain": "data",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing data entities used by each business capability",
        "description_ar": "مصفوفة توضح كيانات البيانات المستخدمة من قبل كل قدرة",
        "building_blocks": ["DataObject", "BusinessCapability"],
        "target_route": "/reports/matrix?source=DataObject&target=BusinessCapability",
        "status": "partial",
        "sort_order": 28,
    },
    {
        "code": "DAT_ENTITY_APP_MTX",
        "name_en": "Data Entity/Applications",
        "name_ar": "كيان البيانات / التطبيقات",
        "domain": "data",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing CRUD relationships between data entities and applications",
        "description_ar": "مصفوفة توضح علاقات إنشاء وقراءة وتحديث وحذف بين كيانات البيانات والتطبيقات",
        "building_blocks": ["DataObject", "Application"],
        "target_route": "/reports/matrix?source=DataObject&target=Application",
        "status": "available",
        "sort_order": 29,
    },
    {
        "code": "DAT_VOCAB_LIST",
        "name_en": "Data Vocabulary",
        "name_ar": "مفردات البيانات",
        "domain": "data",
        "level": "physical",
        "type": "list",
        "description_en": "Dictionary of data terms, definitions, and business meanings",
        "description_ar": "قاموس مصطلحات البيانات والتعريفات والمعاني التجارية",
        "building_blocks": ["DataDictionary", "DataTerm"],
        "target_route": "/inventory?type=DataDictionary",
        "status": "available",
        "sort_order": 30,
    },
    {
        "code": "DAT_VAULT_LIST",
        "name_en": "Data Vaults Catalog",
        "name_ar": "كتالوج مستودعات البيانات",
        "domain": "data",
        "level": "physical",
        "type": "list",
        "description_en": "List of data storage locations, technologies, and capacity",
        "description_ar": "قائمة بمواقع تخزين البيانات والتقنيات والسعة",
        "building_blocks": ["DataVault"],
        "target_route": "/inventory?type=DataVault",
        "status": "missing",
        "sort_order": 31,
    },
    {
        "code": "DAT_ENTITY_ATTR_MTX",
        "name_en": "Data Entity/Data Attributes",
        "name_ar": "كيان البيانات / خصائص البيانات",
        "domain": "data",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing attributes of each data entity with types and constraints",
        "description_ar": "مصفوفة توضح خصائص كل كيان بيانات مع الأنواع والقيود",
        "building_blocks": ["DataObject", "DataAttribute"],
        "target_route": "/reports/matrix?source=DataObject&target=DataAttribute",
        "status": "missing",
        "sort_order": 32,
    },
    {
        "code": "DAT_ENTITY_VAULT_MTX",
        "name_en": "Data Entity/Data Vault",
        "name_ar": "كيان البيانات / مستودع البيانات",
        "domain": "data",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing which data entities are stored in which data vaults",
        "description_ar": "مصفوفة توضح كيانات البيانات المخزنة في كل مستودع",
        "building_blocks": ["DataObject", "DataVault"],
        "target_route": "/reports/matrix?source=DataObject&target=DataVault",
        "status": "missing",
        "sort_order": 33,
    },
    # Applications (14)
    {
        "code": "APP_LANDSCAPE",
        "name_en": "Applications Landscape",
        "name_ar": "منظر التطبيقات",
        "domain": "applications",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing application portfolio with current/target state and organization filters",
        "description_ar": "رسم توضيحي لمحفظة التطبيقات مع الحالة الحالية والمستهدفة",
        "building_blocks": ["Application"],
        "target_route": "/reports/portfolio",
        "status": "available",
        "sort_order": 34,
    },
    {
        "code": "APP_CATALOG",
        "name_en": "Applications Catalog",
        "name_ar": "كتالوج التطبيقات",
        "domain": "applications",
        "level": "logical",
        "type": "list",
        "description_en": "Inventory of applications with ARM fields and required columns",
        "description_ar": "قائمة التطبيقات مع حقول إدارة موارد التطبيقات والأعمدة المطلوبة",
        "building_blocks": ["Application"],
        "target_route": "/inventory?type=Application",
        "status": "available",
        "sort_order": 35,
    },
    {
        "code": "APP_BENEF_MTX",
        "name_en": "Application/Beneficiary",
        "name_ar": "التطبيق / المستفيد",
        "domain": "applications",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing which applications serve each beneficiary segment",
        "description_ar": "مصفوفة توضح التطبيقات التي تخدم كل شريحة مستفيد",
        "building_blocks": ["Application", "Beneficiary"],
        "target_route": "/reports/matrix?source=Application&target=Beneficiary",
        "status": "missing",
        "sort_order": 36,
    },
    {
        "code": "APP_ORG_MTX",
        "name_en": "Application/Organizational Unit",
        "name_ar": "التطبيق / الوحدة التنظيمية",
        "domain": "applications",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing application ownership and usage by organizational units",
        "description_ar": "مصفوفة توضح ملكية التطبيقات والاستخدام من قبل الوحدات التنظيمية",
        "building_blocks": ["Application", "Organization"],
        "target_route": "/reports/matrix?source=Application&target=Organization",
        "status": "available",
        "sort_order": 37,
    },
    {
        "code": "APP_SVC_MTX",
        "name_en": "Application/Business Service",
        "name_ar": "التطبيق / الخدمة الحكومية",
        "domain": "applications",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing applications supporting each government service",
        "description_ar": "مصفوفة توضح التطبيقات التي تدعم كل خدمة حكومية",
        "building_blocks": ["Application", "GovService"],
        "target_route": "/reports/matrix?source=Application&target=GovService",
        "status": "missing",
        "sort_order": 38,
    },
    {
        "code": "APP_PROC_MTX",
        "name_en": "Application/Business Process",
        "name_ar": "التطبيق / العملية الحكومية",
        "domain": "applications",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing applications used in each business process",
        "description_ar": "مصفوفة توضح التطبيقات المستخدمة في كل عملية حكومية",
        "building_blocks": ["Application", "BusinessProcess"],
        "target_route": "/reports/matrix?source=Application&target=BusinessProcess",
        "status": "available",
        "sort_order": 39,
    },
    {
        "code": "APP_SERVER_MTX",
        "name_en": "Application/Server",
        "name_ar": "التطبيق / الخادم",
        "domain": "applications",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing application deployment to server infrastructure",
        "description_ar": "مصفوفة توضح نشر التطبيقات على بنية الخادم",
        "building_blocks": ["Application", "ITComponent"],
        "target_route": "/reports/matrix?source=Application&target=ITComponent&subtype=Server",
        "status": "partial",
        "sort_order": 40,
    },
    {
        "code": "APP_ORG_LAND",
        "name_en": "Applications Viewpoint by Organizational Unit",
        "name_ar": "منظر التطبيقات حسب الوحدة التنظيمية",
        "domain": "applications",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing application landscape filtered by organizational unit",
        "description_ar": "رسم توضيحي لمنظر التطبيقات مرشح حسب الوحدة التنظيمية",
        "building_blocks": ["Application", "Organization"],
        "target_route": "/reports/portfolio?filter=organization",
        "status": "partial",
        "sort_order": 41,
    },
    {
        "code": "APP_MODULES_LAND",
        "name_en": "Landscape of Application Modules",
        "name_ar": "منظر وحدات التطبيق",
        "domain": "applications",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing application components and module hierarchy",
        "description_ar": "رسم توضيحي لمكونات التطبيق والتسلسل الهرمي للوحدات",
        "building_blocks": ["Application"],
        "target_route": "/inventory?type=Application&view=hierarchy",
        "status": "partial",
        "sort_order": 42,
    },
    {
        "code": "APP_INTEGRATION_LAND",
        "name_en": "Integration Landscape",
        "name_ar": "منظر التكامل",
        "domain": "applications",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing interoperability and integration patterns between applications",
        "description_ar": "رسم توضيحي يظهر أنماط التوافق والتكامل بين التطبيقات",
        "building_blocks": ["Application", "Interface"],
        "target_route": "/reports/dependencies?type=Application",
        "status": "available",
        "sort_order": 43,
    },
    {
        "code": "APP_INTEGRATION_VIEWPOINT",
        "name_en": "Applications Integration Viewpoint",
        "name_ar": "منظر تكامل التطبيقات",
        "domain": "applications",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing app-to-app relationships with protocol, direction, frequency overlays",
        "description_ar": "رسم توضيحي للعلاقات بين التطبيقات مع البروتوكول والاتجاه والتكرار",
        "building_blocks": ["Application"],
        "target_route": "/reports/dependencies?type=Application&view=integration",
        "status": "available",
        "sort_order": 44,
    },
    {
        "code": "APP_INTEGRATION_POINTS",
        "name_en": "Technical Integration Point Register",
        "name_ar": "سجل نقاط التكامل التقنية",
        "domain": "applications",
        "level": "physical",
        "type": "list",
        "description_en": "Inventory of interfaces/APIs with protocols, endpoints, and data contracts",
        "description_ar": "قائمة الواجهات والـ API مع البروتوكولات والنقاط النهائية والعقود",
        "building_blocks": ["Interface"],
        "target_route": "/inventory?type=Interface",
        "status": "available",
        "sort_order": 45,
    },
    {
        "code": "APP_SECURITY_SW_MTX",
        "name_en": "Application/Security Software",
        "name_ar": "التطبيق / برنامج الأمان",
        "domain": "applications",
        "level": "physical",
        "type": "matrix",
        "description_en": "Matrix showing security software protecting each application",
        "description_ar": "مصفوفة توضح برنامج الأمان الذي يحمي كل تطبيق",
        "building_blocks": ["Application", "ITComponent"],
        "target_route": "/reports/matrix?source=Application&target=ITComponent&subtype=SecuritySoftware",
        "status": "partial",
        "sort_order": 46,
    },
    {
        "code": "APP_DEVTYPE_SRCTYPE",
        "name_en": "Applications Viewpoint by Development Type Showing the Source Type",
        "name_ar": "منظر التطبيقات حسب نوع التطوير وإظهار نوع المصدر",
        "domain": "applications",
        "level": "physical",
        "type": "diagram",
        "description_en": "Diagram showing applications grouped by development type and source (custom/COTS/SaaS)",
        "description_ar": "رسم توضيحي يظهر التطبيقات مجمعة حسب نوع التطوير والمصدر",
        "building_blocks": ["Application"],
        "target_route": "/reports/portfolio?groupBy=developmentType",
        "status": "partial",
        "sort_order": 47,
    },
    # Technology (12)
    {
        "code": "TECH_DATACENTER_DIST",
        "name_en": "Landscape of Datacenter Distribution",
        "name_ar": "منظر توزيع مراكز البيانات",
        "domain": "technology",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing geographical distribution of data centers and infrastructure",
        "description_ar": "رسم توضيحي لتوزيع مراكز البيانات والبنية التحتية جغرافياً",
        "building_blocks": ["Datacenter", "Location"],
        "target_route": "/reports/datacenter-distribution",
        "status": "available",
        "sort_order": 48,
    },
    {
        "code": "TECH_CAP_LAND",
        "name_en": "Landscape of Technology Architecture Capabilities",
        "name_ar": "منظر قدرات معمارية التكنولوجيا",
        "domain": "technology",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing technology reference models and capability landscape",
        "description_ar": "رسم توضيحي للنماذج المرجعية التكنولوجية ومنظر القدرات",
        "building_blocks": ["TechCategory"],
        "target_route": "/reports/capability-map?type=Technology",
        "status": "partial",
        "sort_order": 49,
    },
    {
        "code": "TECH_TOOLS_CATALOG",
        "name_en": "Infrastructure Tools Catalog",
        "name_ar": "كتالوج أدوات البنية التحتية",
        "domain": "technology",
        "level": "logical",
        "type": "list",
        "description_en": "Inventory of infrastructure tools, software, and platforms with lifecycle",
        "description_ar": "قائمة أدوات البنية التحتية والبرامج والأنظمة الأساسية مع دورة الحياة",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&category=Tool",
        "status": "available",
        "sort_order": 50,
    },
    {
        "code": "TECH_SERVICES_CATALOG",
        "name_en": "Infrastructure Services Catalog",
        "name_ar": "كتالوج خدمات البنية التحتية",
        "domain": "technology",
        "level": "logical",
        "type": "list",
        "description_en": "Catalog of cloud services (IaaS, PaaS, SaaS) with provider and pricing",
        "description_ar": "كتالوج خدمات السحابة (IaaS, PaaS, SaaS) مع المزود والسعر",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=Service",
        "status": "available",
        "sort_order": 51,
    },
    {
        "code": "TECH_DC_PROVIDER_MTX",
        "name_en": "Datacenter/Service Provider",
        "name_ar": "مركز البيانات / مزود الخدمة",
        "domain": "technology",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing datacenters and their service providers",
        "description_ar": "مصفوفة توضح مراكز البيانات ومزودو خدماتهم",
        "building_blocks": ["Datacenter", "Provider"],
        "target_route": "/reports/matrix?source=Datacenter&target=Provider",
        "status": "partial",
        "sort_order": 52,
    },
    {
        "code": "TECH_DC_APP_MTX",
        "name_en": "Datacenter/Application",
        "name_ar": "مركز البيانات / التطبيق",
        "domain": "technology",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing applications deployed to each datacenter",
        "description_ar": "مصفوفة توضح التطبيقات المنشورة في كل مركز بيانات",
        "building_blocks": ["Datacenter", "Application"],
        "target_route": "/reports/matrix?source=Datacenter&target=Application",
        "status": "partial",
        "sort_order": 53,
    },
    {
        "code": "TECH_NETWORK_ARCH",
        "name_en": "Network Architecture Landscape",
        "name_ar": "منظر معمارية الشبكة",
        "domain": "technology",
        "level": "logical",
        "type": "diagram",
        "description_en": "Diagram showing network topology, circuits, and connectivity",
        "description_ar": "رسم توضيحي لطوبولوجيا الشبكة والدوائر والاتصالية",
        "building_blocks": ["NetworkCircuit"],
        "target_route": "/reports/dependencies?type=Network",
        "status": "partial",
        "sort_order": 54,
    },
    {
        "code": "TECH_HOST_CATALOG",
        "name_en": "Physical Host Hardware Catalog",
        "name_ar": "كتالوج أجهزة الخادم المادية",
        "domain": "technology",
        "level": "physical",
        "type": "list",
        "description_en": "Inventory of physical servers and hardware with EOL tracking",
        "description_ar": "قائمة الخوادم المادية والأجهزة مع تتبع نهاية الحياة",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=PhysicalHost",
        "status": "available",
        "sort_order": 55,
    },
    {
        "code": "TECH_SERVERS_CATALOG",
        "name_en": "Servers Catalog",
        "name_ar": "كتالوج الخوادم",
        "domain": "technology",
        "level": "physical",
        "type": "list",
        "description_en": "Inventory of server infrastructure with specifications and locations",
        "description_ar": "قائمة البنية التحتية للخوادم مع المواصفات والمواقع",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=Server",
        "status": "available",
        "sort_order": 56,
    },
    {
        "code": "TECH_NETWORK_DEVICES_CATALOG",
        "name_en": "Network Devices Catalog",
        "name_ar": "كتالوج أجهزة الشبكة",
        "domain": "technology",
        "level": "physical",
        "type": "list",
        "description_en": "Inventory of network switches, routers, and connectivity devices",
        "description_ar": "قائمة مفاتيح الشبكة والموجهات وأجهزة الاتصالية",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=NetworkDevice",
        "status": "available",
        "sort_order": 57,
    },
    {
        "code": "TECH_STORAGE_CATALOG",
        "name_en": "Storage Catalog",
        "name_ar": "كتالوج التخزين",
        "domain": "technology",
        "level": "physical",
        "type": "list",
        "description_en": "Inventory of storage systems and devices with capacity and performance",
        "description_ar": "قائمة أنظمة وأجهزة التخزين مع السعة والأداء",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=Storage",
        "status": "available",
        "sort_order": 58,
    },
    {
        "code": "TECH_NETWORK_CIRCUITS",
        "name_en": "Diagram of Network Connectivity Circuits",
        "name_ar": "رسم توضيحي لدوائر الاتصالية",
        "domain": "technology",
        "level": "physical",
        "type": "diagram",
        "description_en": "Diagram showing network circuits, endpoints, bandwidth, and redundancy",
        "description_ar": "رسم توضيحي لدوائر الشبكة والنقاط النهائية والنطاق الترددي والتكرار",
        "building_blocks": ["NetworkCircuit"],
        "target_route": "/reports/network-topology",
        "status": "available",
        "sort_order": 59,
    },
    # Security (8)
    {
        "code": "SEC_SERVICE_PROVIDER_MTX",
        "name_en": "Security Service/Service Provider",
        "name_ar": "خدمة الأمان / مزود الخدمة",
        "domain": "security",
        "level": "conceptual",
        "type": "matrix",
        "description_en": "Matrix showing security services and their providers",
        "description_ar": "مصفوفة توضح خدمات الأمان ومزودوها",
        "building_blocks": ["SecurityService", "Provider"],
        "target_route": "/reports/matrix?source=SecurityService&target=Provider",
        "status": "partial",
        "sort_order": 60,
    },
    {
        "code": "SEC_ARCHITECTURE_CAP_LAND",
        "name_en": "Landscape of Security Architecture Capabilities",
        "name_ar": "منظر قدرات معمارية الأمان",
        "domain": "security",
        "level": "conceptual",
        "type": "diagram",
        "description_en": "Diagram showing security capabilities and reference models",
        "description_ar": "رسم توضيحي لقدرات الأمان والنماذج المرجعية",
        "building_blocks": ["SecurityService"],
        "target_route": "/reports/capability-map?type=Security",
        "status": "partial",
        "sort_order": 61,
    },
    {
        "code": "SEC_HW_CATALOG",
        "name_en": "Security Hardware Catalog",
        "name_ar": "كتالوج أجهزة الأمان",
        "domain": "security",
        "level": "logical",
        "type": "list",
        "description_en": "Inventory of security hardware (firewalls, IDS, encryption devices)",
        "description_ar": "قائمة أجهزة الأمان (جدران الحماية وكواشف التطفل)",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=SecurityHardware",
        "status": "available",
        "sort_order": 62,
    },
    {
        "code": "SEC_SW_CATALOG",
        "name_en": "Security Software Catalog",
        "name_ar": "كتالوج برنامج الأمان",
        "domain": "security",
        "level": "logical",
        "type": "list",
        "description_en": "Inventory of security software (antivirus, WAF, SIEM)",
        "description_ar": "قائمة برنامج الأمان (مضادات الفيروسات، جدران تطبيقات الويب، SIEM)",
        "building_blocks": ["ITComponent"],
        "target_route": "/inventory?type=ITComponent&subtype=SecuritySoftware",
        "status": "available",
        "sort_order": 63,
    },
    {
        "code": "SEC_SERVICES_CATALOG",
        "name_en": "Security Services Catalog",
        "name_ar": "كتالوج خدمات الأمان",
        "domain": "security",
        "level": "logical",
        "type": "list",
        "description_en": "Catalog of security services (managed security, consulting, monitoring)",
        "description_ar": "كتالوج خدمات الأمان (الأمان المدار والاستشارات والمراقبة)",
        "building_blocks": ["SecurityService"],
        "target_route": "/inventory?type=SecurityService",
        "status": "partial",
        "sort_order": 64,
    },
    {
        "code": "SEC_HW_SW_FUNC_LOCATIONS_MTX",
        "name_en": "Security Hardware and Software Function / Application Locations",
        "name_ar": "وظيفة أجهزة وبرامج الأمان / مواقع التطبيقات",
        "domain": "security",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing security functions and their deployment locations",
        "description_ar": "مصفوفة توضح وظائف الأمان ومواقع نشرها",
        "building_blocks": ["SecurityFunction", "Location"],
        "target_route": "/reports/matrix?source=SecurityFunction&target=Location",
        "status": "missing",
        "sort_order": 65,
    },
    {
        "code": "SEC_HW_SW_FUNC_APPS_MTX",
        "name_en": "Security Hardware and Software Functions / Related Applications",
        "name_ar": "وظائف أجهزة وبرامج الأمان / التطبيقات المرتبطة",
        "domain": "security",
        "level": "logical",
        "type": "matrix",
        "description_en": "Matrix showing security functions protecting applications",
        "description_ar": "مصفوفة توضح وظائف الأمان التي تحمي التطبيقات",
        "building_blocks": ["SecurityFunction", "Application"],
        "target_route": "/reports/matrix?source=SecurityFunction&target=Application",
        "status": "partial",
        "sort_order": 66,
    },
    {
        "code": "SEC_HW_DC_DIST",
        "name_en": "Distribution of Security Hardware in Datacenters",
        "name_ar": "توزيع أجهزة الأمان في مراكز البيانات",
        "domain": "security",
        "level": "physical",
        "type": "diagram",
        "description_en": "Diagram showing security hardware deployment across datacenters",
        "description_ar": "رسم توضيحي لنشر أجهزة الأمان عبر مراكز البيانات",
        "building_blocks": ["SecurityHardware", "Datacenter"],
        "target_route": "/reports/security-deployment",
        "status": "available",
        "sort_order": 67,
    },
]


async def seed_nora_viewpoints(db: AsyncSession) -> None:
    """Seed all 67 NORA viewpoints into viewpoint_definitions table.

    Called on startup to ensure the View Library has complete metadata.
    Idempotent — skips rows with existing codes.
    """
    for vp_data in NORA_VIEWPOINTS:
        existing = await db.execute(
            select(ViewpointDefinition).where(ViewpointDefinition.code == vp_data["code"])
        )
        if existing.scalars().first() is None:
            vp = ViewpointDefinition(**vp_data)
            db.add(vp)

    await db.commit()
