/**
 * Create-Workspace dialog.
 *
 * The workspace's own UUID is generated by the backend automatically. The
 * two picker fields ("Linked SoAW", "Linked Initiative") are for choosing
 * an *existing* SoAW / Initiative to anchor the workspace to — not for
 * typing raw UUIDs. When ``soawId`` is supplied by the caller (the SoAW
 * editor path) the anchor is pre-filled and both pickers are hidden.
 *
 * [FORK FEATURE]
 */

import { useEffect, useMemo, useState } from "react";
import Alert from "@mui/material/Alert";
import Autocomplete from "@mui/material/Autocomplete";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Dialog from "@mui/material/Dialog";
import DialogActions from "@mui/material/DialogActions";
import DialogContent from "@mui/material/DialogContent";
import DialogTitle from "@mui/material/DialogTitle";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import { useTranslation } from "react-i18next";
import CardPicker, { type CardOption } from "@/components/CardPicker";
import { api, ApiError } from "@/api/client";
import type { AdmWorkspace } from "./types";

/** Minimal shape returned by GET /soaw for the autocomplete. */
interface SoawOption {
  id: string;
  name: string;
  status?: string;
  doc_type?: string;
}

interface Props {
  open: boolean;
  soawId?: string;
  soawName?: string;
  /** Reserved for a future "from an Initiative card" entry point. */
  initiativeId?: string;
  onClose: () => void;
  onCreated: (workspaceId: string) => void;
}

export default function CreateWorkspaceDialog({
  open,
  soawId,
  soawName,
  initiativeId: _initiativeId,
  onClose,
  onCreated,
}: Props) {
  const { t } = useTranslation(["adm", "common"]);
  const [name, setName] = useState("");
  // Tracks whether the user has typed in the name field. If they have,
  // auto-fill from the picked SoAW is suppressed so we don't overwrite
  // their intent.
  const [nameEdited, setNameEdited] = useState(false);
  const [description, setDescription] = useState("");
  const [soaws, setSoaws] = useState<SoawOption[]>([]);
  const [soawsLoading, setSoawsLoading] = useState(false);
  const [pickedSoaw, setPickedSoaw] = useState<SoawOption | null>(null);
  const [pickedInitiative, setPickedInitiative] = useState<CardOption | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Reset state on every open, and pre-fill the anchor when the caller
  // supplied one (SoAW-editor path).
  useEffect(() => {
    if (!open) return;
    setName(soawName ? `${soawName} — ADM` : "");
    setNameEdited(false);
    setDescription("");
    setPickedInitiative(null);
    setError(null);
    setBusy(false);
    if (soawId) {
      // Represent the pre-filled anchor as a fully-formed picker value so
      // the (hidden) submit logic still finds it.
      setPickedSoaw({ id: soawId, name: soawName ?? soawId });
    } else {
      setPickedSoaw(null);
    }
  }, [open, soawId, soawName]);

  // Auto-fill the name when the user picks a SoAW from the dropdown, so
  // they don't have to type one. Skipped when they've already typed
  // something (nameEdited) or when the caller pre-filled the anchor.
  useEffect(() => {
    if (soawId) return;
    if (nameEdited) return;
    if (pickedSoaw) {
      setName(`${pickedSoaw.name} — ADM`);
    } else if (pickedInitiative) {
      setName(`${pickedInitiative.name} — ADM`);
    } else {
      setName("");
    }
  }, [soawId, nameEdited, pickedSoaw, pickedInitiative]);

  // Load existing SoAWs once when the dialog opens (only when the caller
  // hasn't pre-filled the anchor). The list is small, so we fetch all and
  // let the Autocomplete filter client-side.
  useEffect(() => {
    if (!open || soawId) return;
    let cancelled = false;
    setSoawsLoading(true);
    api
      .get<SoawOption[]>("/soaw")
      .then((rows) => {
        if (cancelled) return;
        setSoaws(rows);
      })
      .catch((e) => {
        if (cancelled) return;
        // Fall back to an empty list; the Initiative picker still works.
        if (e instanceof ApiError) {
          setError(typeof e.detail === "string" ? e.detail : e.message);
        }
      })
      .finally(() => {
        if (!cancelled) setSoawsLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [open, soawId]);

  const canSubmit = useMemo(
    () => name.trim().length > 0 && (pickedSoaw !== null || pickedInitiative !== null),
    [name, pickedSoaw, pickedInitiative],
  );

  const submit = async () => {
    setBusy(true);
    setError(null);
    try {
      const payload: Record<string, unknown> = {
        name: name.trim(),
        template: "togaf",
      };
      if (description.trim()) payload.description = description.trim();
      if (pickedSoaw) payload.soaw_id = pickedSoaw.id;
      if (pickedInitiative) payload.initiative_id = pickedInitiative.id;
      const created = await api.post<AdmWorkspace>("/adm/workspaces", payload);
      onCreated(created.id);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm" disableRestoreFocus>
      <DialogTitle>{t("create.title")}</DialogTitle>
      <DialogContent sx={{ display: "flex", flexDirection: "column", gap: 2, pt: 1 }}>
        <Typography variant="body2" color="text.secondary">
          {t("create.subtitle")}
        </Typography>

        <TextField
          label={t("create.name")}
          value={name}
          onChange={(e) => {
            setName(e.target.value);
            setNameEdited(true);
          }}
          required
          autoFocus
          helperText={
            !name.trim() && (pickedSoaw || pickedInitiative)
              ? t("create.nameHelperEmpty")
              : t("create.nameHelper")
          }
          error={!name.trim() && (pickedSoaw !== null || pickedInitiative !== null)}
        />
        <TextField
          label={t("create.description")}
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          multiline
          minRows={2}
        />

        {/* Anchor pickers — hidden when the caller pre-filled the SoAW
            (the "from SoAW editor" path). */}
        {!soawId && (
          <>
            <Typography variant="caption" color="text.secondary" sx={{ mt: 1 }}>
              {t("create.anchorSection")}
            </Typography>

            <Autocomplete<SoawOption>
              options={soaws}
              value={pickedSoaw}
              onChange={(_, v) => setPickedSoaw(v)}
              getOptionLabel={(o) => o.name}
              isOptionEqualToValue={(a, b) => a.id === b.id}
              loading={soawsLoading}
              renderOption={(props, option) => (
                <Box component="li" {...props}>
                  <Box sx={{ display: "flex", flexDirection: "column", flex: 1, minWidth: 0 }}>
                    <Typography variant="body2" noWrap>
                      {option.name}
                    </Typography>
                    {option.status && (
                      <Typography variant="caption" color="text.secondary">
                        {option.status}
                        {option.doc_type && option.doc_type !== "soaw"
                          ? ` · ${option.doc_type}`
                          : ""}
                      </Typography>
                    )}
                  </Box>
                </Box>
              )}
              renderInput={(params) => (
                <TextField
                  {...params}
                  label={t("create.soawPicker")}
                  helperText={t("create.soawPickerHelper")}
                />
              )}
            />

            <CardPicker
              types="Initiative"
              value={pickedInitiative}
              onChange={setPickedInitiative}
              label={t("create.initiativePicker")}
              helperText={t("create.initiativePickerHelper")}
              size="medium"
              fullWidth
            />

            {(pickedSoaw || pickedInitiative) && (
              <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
                {pickedSoaw && (
                  <Chip
                    size="small"
                    color="primary"
                    variant="outlined"
                    label={`${t("create.selectedSoaw")}: ${pickedSoaw.name}`}
                    onDelete={() => setPickedSoaw(null)}
                  />
                )}
                {pickedInitiative && (
                  <Chip
                    size="small"
                    color="primary"
                    variant="outlined"
                    label={`${t("create.selectedInitiative")}: ${pickedInitiative.name}`}
                    onDelete={() => setPickedInitiative(null)}
                  />
                )}
              </Box>
            )}
          </>
        )}

        {error && <Alert severity="error">{error}</Alert>}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={busy}>
          {t("actions.cancel", { ns: "common" })}
        </Button>
        <Button variant="contained" onClick={submit} disabled={!canSubmit || busy}>
          {t("create.submit")}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
