/**
 * NEA viewpoint registry — the ~47 core viewpoints of the EA Viewpoints
 * Document (Dec 2024, v2.0, §5.4) mapped to the Turbo EA view that produces
 * each one. Data-driven: the View Library renders this list; nothing here is
 * a hardcoded page.
 *
 * Viewpoint names are bilingual data (en/ar, from the document itself), like
 * program-deliverable titles — only UI chrome is i18n-translated.
 *
 * `status`:
 *  - "available" — `path` deep-links to the view that produces it
 *  - "planned"   — no dedicated renderer yet; `path` (when set) is the
 *                  closest existing view
 *  - "descoped"  — rests on a building block the NORA plan deliberately
 *                  descoped (Position/Role, Beneficiary registry, Template,
 *                  Data Attributes, Network Link)
 *
 * `methodology` — the phase-step linkage from the document ("2.3" = document
 * current-state building blocks & viewpoints, "4.2" = detail target
 * building blocks & viewpoints; nearly every viewpoint serves both).
 *
 * [FORK FEATURE] — noraPlan.md WP6.7.
 */

export type NeaDomain =
  | "strategic"
  | "business"
  | "beneficiaryExperience"
  | "data"
  | "applications"
  | "technology"
  | "security";

export type NeaViewpointKind = "list" | "matrix" | "diagram";
export type NeaLevel = "conceptual" | "logical" | "physical";
export type NeaStatus = "available" | "planned" | "descoped";

export interface NeaViewpoint {
  key: string;
  domain: NeaDomain;
  kind: NeaViewpointKind;
  level: NeaLevel;
  nameEn: string;
  nameAr: string;
  /** Deep-link to the Turbo EA view that produces this viewpoint. */
  path?: string;
  status: NeaStatus;
}

export const NEA_VIEWPOINTS: NeaViewpoint[] = [
  // ── Strategic Alignment ─────────────────────────────────────────────────
  {
    key: "strategic-objectives-catalog",
    domain: "strategic",
    kind: "list",
    level: "conceptual",
    nameEn: "Strategic Objectives Catalog",
    nameAr: "دليل الأهداف الاستراتيجية",
    path: "/inventory?type=Objective",
    status: "available",
  },
  {
    key: "objectives-pillars",
    domain: "strategic",
    kind: "matrix",
    level: "conceptual",
    nameEn: "Objectives / Pillars",
    nameAr: "الأهداف / الركائز",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "strategic-house",
    domain: "strategic",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Strategic House",
    nameAr: "البيت الاستراتيجي",
    path: "/reports/strategic-house",
    status: "available",
  },
  // ── Business ────────────────────────────────────────────────────────────
  {
    key: "service-catalog",
    domain: "business",
    kind: "list",
    level: "conceptual",
    nameEn: "Service Catalog",
    nameAr: "دليل الخدمات",
    path: "/reports/service-catalogue",
    status: "available",
  },
  {
    key: "organizational-structure",
    domain: "business",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Organizational Structure",
    nameAr: "الهيكل التنظيمي",
    path: "/reports/org-chart",
    status: "available",
  },
  {
    key: "business-value-chain",
    domain: "business",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Business Value Chain",
    nameAr: "سلسلة القيمة للأعمال",
    path: "/reports/value-chain",
    status: "available",
  },
  {
    key: "business-processes-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Business Processes Catalog",
    nameAr: "دليل إجراءات الأعمال",
    path: "/inventory?type=BusinessProcess",
    status: "available",
  },
  {
    key: "model-template-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Model / Template Catalog",
    nameAr: "دليل النماذج والقوالب",
    status: "descoped",
  },
  {
    key: "policy-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Policy Catalog",
    nameAr: "دليل السياسات",
    path: "/inventory?type=Policy",
    status: "available",
  },
  {
    key: "org-units-services",
    domain: "business",
    kind: "matrix",
    level: "logical",
    nameEn: "Organizational Units / Services",
    nameAr: "الوحدات التنظيمية / الخدمات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "capabilities-org-units",
    domain: "business",
    kind: "matrix",
    level: "logical",
    nameEn: "Business Capabilities / Organizational Units",
    nameAr: "قدرات الأعمال / الوحدات التنظيمية",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "interaction-model",
    domain: "business",
    kind: "diagram",
    level: "logical",
    nameEn: "Interaction Model for the Entity / Organizational Unit",
    nameAr: "نموذج التفاعل للجهة / الوحدة التنظيمية",
    path: "/reports/dependencies",
    status: "planned",
  },
  {
    key: "mandates-positions",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Mandates / Positions",
    nameAr: "التكليفات / الوظائف",
    status: "descoped",
  },
  {
    key: "services-models",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Models",
    nameAr: "الخدمات / النماذج",
    status: "descoped",
  },
  {
    key: "services-processes",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Business Processes",
    nameAr: "الخدمات / إجراءات الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "services-applications",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Applications",
    nameAr: "الخدمات / التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "business-process-diagram",
    domain: "business",
    kind: "diagram",
    level: "physical",
    nameEn: "Business Process Diagram",
    nameAr: "مخطط إجراءات الأعمال",
    path: "/bpm",
    status: "available",
  },
  // ── Beneficiary Experience ──────────────────────────────────────────────
  {
    key: "persona-card",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Beneficiary Persona Card",
    nameAr: "بطاقة شخصية المستفيد",
    path: "/inventory?type=Persona",
    status: "available",
  },
  {
    key: "journey-improvements-list",
    domain: "beneficiaryExperience",
    kind: "list",
    level: "logical",
    nameEn: "List of Improvements to Beneficiary Journeys",
    nameAr: "قائمة تحسينات رحلات المستفيد",
    path: "/grc?tab=governance",
    status: "available",
  },
  {
    key: "beneficiaries-personas",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Beneficiaries / Beneficiary Personas",
    nameAr: "المستفيدون / شخصيات المستفيد",
    status: "descoped",
  },
  {
    key: "services-personas",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Services / Beneficiary Personas",
    nameAr: "الخدمات / شخصيات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "services-journeys",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Services / Beneficiary Journeys",
    nameAr: "الخدمات / رحلات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "personas-journeys",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Beneficiary Personas / Beneficiary Journeys",
    nameAr: "شخصيات المستفيد / رحلات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "journey-map",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "logical",
    nameEn: "Beneficiary Journey Map",
    nameAr: "خريطة رحلة المستفيد",
    path: "/inventory?type=BeneficiaryJourney",
    status: "available",
  },
  {
    key: "journeys-improvement-priorities",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "physical",
    nameEn: "Beneficiary Journeys / Experience Improvement Priorities",
    nameAr: "رحلات المستفيد / أولويات تحسين التجربة",
    path: "/grc?tab=governance",
    status: "available",
  },
  // ── Data ────────────────────────────────────────────────────────────────
  {
    key: "data-entities-landscape",
    domain: "data",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Data Entities Landscape",
    nameAr: "المشهد العام لكيانات البيانات",
    path: "/layers/data",
    status: "available",
  },
  {
    key: "data-owners-list",
    domain: "data",
    kind: "list",
    level: "logical",
    nameEn: "List of Data Owners",
    nameAr: "قائمة ملاك البيانات",
    path: "/inventory?type=DataObject",
    status: "available",
  },
  {
    key: "data-entity-capability",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Entity / Business Capability",
    nameAr: "كيان البيانات / قدرة الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "data-entity-applications",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Entity / Applications",
    nameAr: "كيان البيانات / التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "data-vocabulary",
    domain: "data",
    kind: "list",
    level: "physical",
    nameEn: "Data Vocabulary",
    nameAr: "قاموس البيانات",
    status: "descoped",
  },
  {
    key: "data-vaults-catalog",
    domain: "data",
    kind: "list",
    level: "physical",
    nameEn: "Data Vaults Catalog",
    nameAr: "دليل مستودعات البيانات",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "data-entity-attributes",
    domain: "data",
    kind: "matrix",
    level: "physical",
    nameEn: "Data Entity / Data Attributes",
    nameAr: "كيان البيانات / عناصر البيانات",
    status: "descoped",
  },
  {
    key: "data-entity-vault",
    domain: "data",
    kind: "matrix",
    level: "physical",
    nameEn: "Data Entity / Data Vault",
    nameAr: "كيان البيانات / مستودع البيانات",
    path: "/reports/matrix",
    status: "available",
  },
  // ── Applications ────────────────────────────────────────────────────────
  {
    key: "applications-landscape",
    domain: "applications",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Applications Landscape",
    nameAr: "المشهد العام للتطبيقات",
    path: "/layers/application",
    status: "available",
  },
  {
    key: "applications-catalog",
    domain: "applications",
    kind: "list",
    level: "logical",
    nameEn: "Applications Catalog",
    nameAr: "سجل التطبيقات",
    path: "/inventory?type=Application",
    status: "available",
  },
  {
    key: "application-beneficiary",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Beneficiary",
    nameAr: "التطبيق / المستفيد",
    status: "descoped",
  },
  {
    key: "application-org-unit",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Organizational Unit",
    nameAr: "التطبيق / الوحدة التنظيمية",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-service",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Business Service",
    nameAr: "التطبيق / خدمة الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-process",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Business Process",
    nameAr: "التطبيق / إجراء الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-server",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Server",
    nameAr: "التطبيق / الخادم",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "applications-by-org-unit",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Applications Viewpoint by Organizational Unit",
    nameAr: "منظور التطبيقات حسب الوحدة التنظيمية",
    path: "/reports/matrix",
    status: "planned",
  },
  {
    key: "application-modules-landscape",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Landscape of Application Modules",
    nameAr: "المشهد العام لوحدات التطبيقات",
    path: "/reports/application-modules",
    status: "available",
  },
  {
    key: "integration-landscape",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Integration Landscape",
    nameAr: "المشهد العام للتكامل",
    path: "/reports/interoperability",
    status: "available",
  },
  {
    key: "applications-integration",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Applications Integration Viewpoint",
    nameAr: "منظور تكامل التطبيقات",
    path: "/reports/dependencies",
    status: "available",
  },
  {
    key: "integration-point-register",
    domain: "applications",
    kind: "list",
    level: "physical",
    nameEn: "Technical Integration Point Register",
    nameAr: "سجل نقاط الربط التقني",
    path: "/inventory?type=Interface",
    status: "available",
  },
  {
    key: "application-security-software",
    domain: "applications",
    kind: "matrix",
    level: "physical",
    nameEn: "Application / Security Software",
    nameAr: "التطبيق / برمجيات الأمن",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "applications-by-development-type",
    domain: "applications",
    kind: "diagram",
    level: "physical",
    nameEn: "Applications by Development Type Showing Source Type",
    nameAr: "التطبيقات حسب نوع التطوير ونوع المصدر",
    path: "/reports/flexible-portfolio",
    status: "available",
  },
  // ── Technology ──────────────────────────────────────────────────────────
  {
    key: "datacenter-distribution",
    domain: "technology",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Datacenter Distribution",
    nameAr: "المشهد العام لتوزيع مراكز البيانات",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "technology-capabilities-landscape",
    domain: "technology",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Technology Architecture Capabilities",
    nameAr: "المشهد العام لقدرات بنية التقنية",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "infra-tools-catalog",
    domain: "technology",
    kind: "list",
    level: "logical",
    nameEn: "Infrastructure Tools Catalog",
    nameAr: "دليل أدوات البنية التحتية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "infra-services-catalog",
    domain: "technology",
    kind: "list",
    level: "logical",
    nameEn: "Infrastructure Services Catalog",
    nameAr: "دليل خدمات البنية التحتية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "datacenter-provider",
    domain: "technology",
    kind: "matrix",
    level: "logical",
    nameEn: "Datacenter / Service Provider",
    nameAr: "مركز البيانات / مزود الخدمة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "datacenter-application",
    domain: "technology",
    kind: "matrix",
    level: "logical",
    nameEn: "Datacenter / Application",
    nameAr: "مركز البيانات / التطبيق",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "network-architecture-landscape",
    domain: "technology",
    kind: "diagram",
    level: "logical",
    nameEn: "Network Architecture Landscape",
    nameAr: "المشهد العام لبنية الشبكة",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "physical-host-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Physical Host Hardware Catalog",
    nameAr: "دليل أجهزة المضيفات المادية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "servers-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Servers Catalog",
    nameAr: "دليل الخوادم",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "network-devices-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Network Devices Catalog",
    nameAr: "دليل أجهزة الشبكة",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "storage-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Storage Catalog",
    nameAr: "دليل وحدات التخزين",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "network-connectivity-circuits",
    domain: "technology",
    kind: "diagram",
    level: "physical",
    nameEn: "Diagram of Network Connectivity Circuits",
    nameAr: "مخطط دوائر الربط الشبكي",
    status: "descoped",
  },
  // ── Security ────────────────────────────────────────────────────────────
  {
    key: "security-service-provider",
    domain: "security",
    kind: "matrix",
    level: "conceptual",
    nameEn: "Security Service / Service Provider",
    nameAr: "خدمة الأمن / مزود الخدمة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-capabilities-landscape",
    domain: "security",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Security Architecture Capabilities",
    nameAr: "المشهد العام لقدرات بنية الأمن",
    path: "/layers/security",
    status: "available",
  },
  {
    key: "security-hardware-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Hardware Catalog",
    nameAr: "دليل أجهزة الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-software-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Software Catalog",
    nameAr: "دليل برمجيات الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-services-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Services Catalog",
    nameAr: "دليل خدمات الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-function-locations",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Security Hardware & Software Function / Application Locations",
    nameAr: "وظائف أجهزة وبرمجيات الأمن / مواقع التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-functions-applications",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Security Hardware & Software Functions / Related Applications",
    nameAr: "وظائف أجهزة وبرمجيات الأمن / التطبيقات المرتبطة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-hardware-in-datacenters",
    domain: "security",
    kind: "diagram",
    level: "physical",
    nameEn: "Distribution of Security Hardware in Datacenters",
    nameAr: "توزيع أجهزة الأمن في مراكز البيانات",
    path: "/reports/technology-landscape",
    status: "available",
  },
];

export const NEA_DOMAIN_ORDER: NeaDomain[] = [
  "strategic",
  "business",
  "beneficiaryExperience",
  "data",
  "applications",
  "technology",
  "security",
];
