/**
 * NEA viewpoint registry — the ~47 core viewpoints of the EA Viewpoints
 * Document (Dec 2024, v2.0, §5.4) mapped to the Turbo EA view that produces
 * each one. Data-driven: the View Library renders this list; nothing here is
 * a hardcoded page.
 *
 * Viewpoint names are bilingual data (en/ar, from the document itself), like
 * program-deliverable titles — only UI chrome is i18n-translated.
 *
 * `status`:
 *  - "available" — `path` deep-links to the view that produces it
 *  - "planned"   — no dedicated renderer yet; `path` (when set) is the
 *                  closest existing view
 *  - "descoped"  — rests on a building block the NORA plan deliberately
 *                  descoped (Position/Role, Beneficiary registry, Template,
 *                  Data Attributes, Network Link)
 *
 * `methodology` — the phase-step linkage from the document ("2.3" = document
 * current-state building blocks & viewpoints, "4.2" = detail target
 * building blocks & viewpoints; nearly every viewpoint serves both).
 *
 * [FORK FEATURE] — noraPlan.md WP6.7.
 */

export type NeaDomain =
  | "strategic"
  | "business"
  | "beneficiaryExperience"
  | "data"
  | "applications"
  | "technology"
  | "security";

export type NeaViewpointKind = "list" | "matrix" | "diagram";
export type NeaLevel = "conceptual" | "logical" | "physical";
export type NeaStatus = "available" | "planned" | "descoped";

export interface NeaViewpoint {
  key: string;
  domain: NeaDomain;
  kind: NeaViewpointKind;
  level: NeaLevel;
  nameEn: string;
  nameAr: string;
  /** Plain-language stakeholder question this view answers. */
  questionEn?: string;
  questionAr?: string;
  /** Material Symbol icon name for the View Library card. */
  icon?: string;
  /** Required permission key to launch (e.g., "reports.portfolio"). */
  permission?: string;
  /** Required enabled module ("bpm" | "ppm" | "grc" | "turbolens"). */
  module?: "bpm" | "ppm" | "grc" | "turbolens";
  /** Deep-link to the Turbo EA view that produces this viewpoint. */
  path?: string;
  status: NeaStatus;
}

export const NEA_VIEWPOINTS: NeaViewpoint[] = [
  // ── Strategic Alignment ─────────────────────────────────────────────────
  {
    key: "strategic-objectives-catalog",
    domain: "strategic",
    kind: "list",
    level: "conceptual",
    nameEn: "Strategic Objectives Catalog",
    nameAr: "دليل الأهداف الاستراتيجية",
    questionEn: "What are the organization's strategic objectives?",
    questionAr: "ما هي الأهداف الاستراتيجية للمنظمة؟",
    icon: "flag",
    path: "/inventory?type=Objective",
    status: "available",
  },
  {
    key: "objectives-pillars",
    domain: "strategic",
    kind: "matrix",
    level: "conceptual",
    nameEn: "Objectives / Pillars",
    nameAr: "الأهداف / الركائز",
    questionEn: "How do strategic pillars and objectives map to each other?",
    questionAr: "كيف تتطابق الركائز الاستراتيجية والأهداف مع بعضها البعض؟",
    icon: "grid_3x3",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "strategic-house",
    domain: "strategic",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Strategic House",
    nameAr: "البيت الاستراتيجي",
    questionEn: "How do vision, strategy, and architecture align?",
    questionAr: "كيف يتم محاذاة الرؤية والاستراتيجية والعمارة؟",
    icon: "account_balance",
    path: "/reports/strategic-house",
    status: "available",
  },
  {
    key: "current-vs-target",
    domain: "strategic",
    kind: "matrix",
    level: "conceptual",
    nameEn: "Current vs Target Comparison",
    nameAr: "مقارنة الحالة الحالية بالحالة المستهدفة",
    questionEn: "What is the difference between current and target architectures?",
    questionAr: "ما الفرق بين الهندسة المعمارية الحالية والمستهدفة؟",
    icon: "compare_arrows",
    path: "/reports/current-vs-target",
    status: "available",
  },
  {
    key: "gap-summary",
    domain: "strategic",
    kind: "list",
    level: "conceptual",
    nameEn: "Gap Summary",
    nameAr: "ملخص الفجوات",
    questionEn: "What gaps exist between current and target states?",
    questionAr: "ما هي الفجوات الموجودة بين الحالة الحالية والمستهدفة؟",
    icon: "warning",
    path: "/reports/gap-summary",
    status: "available",
  },
  {
    key: "transition-roadmap",
    domain: "strategic",
    kind: "diagram",
    level: "logical",
    nameEn: "Transition Roadmap by Wave",
    nameAr: "خريطة الطريق للانتقال حسب المرحلة",
    questionEn: "When and how will architecture evolve?",
    questionAr: "متى وكيف ستتطور الهندسة المعمارية؟",
    icon: "timeline",
    path: "/reports/transition-roadmap",
    status: "available",
  },
  {
    key: "target-landscape",
    domain: "strategic",
    kind: "diagram",
    level: "logical",
    nameEn: "Target Architecture Landscape",
    nameAr: "مشهد الهندسة المعمارية المستهدفة",
    questionEn: "What does the target architecture look like?",
    questionAr: "كيف تبدو الهندسة المعمارية المستهدفة؟",
    icon: "architecture",
    path: "/reports/target-landscape",
    status: "available",
  },
  {
    key: "initiative-gap-traceability",
    domain: "strategic",
    kind: "matrix",
    level: "logical",
    nameEn: "Initiative-to-Gap Traceability",
    nameAr: "تتبع المبادرات للفجوات",
    questionEn: "Which initiatives are closing which gaps?",
    questionAr: "أي المبادرات تغلق أي الفجوات؟",
    icon: "connect_without_contact",
    path: "/reports/initiative-gap-traceability",
    status: "available",
  },
  // ── Business ────────────────────────────────────────────────────────────
  {
    key: "service-catalog",
    domain: "business",
    kind: "list",
    level: "conceptual",
    nameEn: "Service Catalog",
    nameAr: "دليل الخدمات",
    questionEn: "What services does the organization offer?",
    questionAr: "ما هي الخدمات التي تقدمها المنظمة؟",
    icon: "construction",
    path: "/reports/service-catalogue",
    status: "available",
  },
  {
    key: "organizational-structure",
    domain: "business",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Organizational Structure",
    nameAr: "الهيكل التنظيمي",
    questionEn: "How is the organization structured?",
    questionAr: "كيف تنظم المنظمة؟",
    icon: "org_chart",
    path: "/reports/org-chart",
    status: "available",
  },
  {
    key: "business-value-chain",
    domain: "business",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Business Value Chain",
    nameAr: "سلسلة القيمة للأعمال",
    questionEn: "How does the organization create value?",
    questionAr: "كيف تنتج المنظمة القيمة؟",
    icon: "trending_up",
    path: "/reports/value-chain",
    status: "available",
  },
  {
    key: "business-processes-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Business Processes Catalog",
    nameAr: "دليل إجراءات الأعمال",
    questionEn: "What are the core business processes?",
    questionAr: "ما هي عمليات الأعمال الأساسية؟",
    icon: "route",
    path: "/inventory?type=BusinessProcess",
    status: "available",
  },
  {
    key: "model-template-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Model / Template Catalog",
    nameAr: "دليل النماذج والقوالب",
    status: "descoped",
  },
  {
    key: "policy-catalog",
    domain: "business",
    kind: "list",
    level: "logical",
    nameEn: "Policy Catalog",
    nameAr: "دليل السياسات",
    path: "/inventory?type=Policy",
    status: "available",
  },
  {
    key: "org-units-services",
    domain: "business",
    kind: "matrix",
    level: "logical",
    nameEn: "Organizational Units / Services",
    nameAr: "الوحدات التنظيمية / الخدمات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "capabilities-org-units",
    domain: "business",
    kind: "matrix",
    level: "logical",
    nameEn: "Business Capabilities / Organizational Units",
    nameAr: "قدرات الأعمال / الوحدات التنظيمية",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "interaction-model",
    domain: "business",
    kind: "diagram",
    level: "logical",
    nameEn: "Interaction Model for the Entity / Organizational Unit",
    nameAr: "نموذج التفاعل للجهة / الوحدة التنظيمية",
    path: "/reports/dependencies",
    status: "planned",
  },
  {
    key: "mandates-positions",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Mandates / Positions",
    nameAr: "التكليفات / الوظائف",
    status: "descoped",
  },
  {
    key: "services-models",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Models",
    nameAr: "الخدمات / النماذج",
    status: "descoped",
  },
  {
    key: "services-processes",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Business Processes",
    nameAr: "الخدمات / إجراءات الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "services-applications",
    domain: "business",
    kind: "matrix",
    level: "physical",
    nameEn: "Services / Applications",
    nameAr: "الخدمات / التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "business-process-diagram",
    domain: "business",
    kind: "diagram",
    level: "physical",
    nameEn: "Business Process Diagram",
    nameAr: "مخطط إجراءات الأعمال",
    path: "/bpm",
    status: "available",
  },
  // ── Beneficiary Experience ──────────────────────────────────────────────
  {
    key: "persona-card",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Beneficiary Persona Card",
    nameAr: "بطاقة شخصية المستفيد",
    path: "/inventory?type=Persona",
    status: "available",
  },
  {
    key: "journey-improvements-list",
    domain: "beneficiaryExperience",
    kind: "list",
    level: "logical",
    nameEn: "List of Improvements to Beneficiary Journeys",
    nameAr: "قائمة تحسينات رحلات المستفيد",
    path: "/grc?tab=governance",
    status: "available",
  },
  {
    key: "beneficiaries-personas",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Beneficiaries / Beneficiary Personas",
    nameAr: "المستفيدون / شخصيات المستفيد",
    status: "descoped",
  },
  {
    key: "services-personas",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Services / Beneficiary Personas",
    nameAr: "الخدمات / شخصيات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "services-journeys",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Services / Beneficiary Journeys",
    nameAr: "الخدمات / رحلات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "personas-journeys",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Beneficiary Personas / Beneficiary Journeys",
    nameAr: "شخصيات المستفيد / رحلات المستفيد",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "journey-map",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "logical",
    nameEn: "Beneficiary Journey Map",
    nameAr: "خريطة رحلة المستفيد",
    path: "/inventory?type=BeneficiaryJourney",
    status: "available",
  },
  {
    key: "journeys-improvement-priorities",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "physical",
    nameEn: "Beneficiary Journeys / Experience Improvement Priorities",
    nameAr: "رحلات المستفيد / أولويات تحسين التجربة",
    path: "/grc?tab=governance",
    status: "available",
  },
  // ── Data ────────────────────────────────────────────────────────────────
  {
    key: "data-entities-landscape",
    domain: "data",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Data Entities Landscape",
    nameAr: "المشهد العام لكيانات البيانات",
    path: "/layers/data",
    status: "available",
  },
  {
    key: "data-owners-list",
    domain: "data",
    kind: "list",
    level: "logical",
    nameEn: "List of Data Owners",
    nameAr: "قائمة ملاك البيانات",
    path: "/inventory?type=DataObject",
    status: "available",
  },
  {
    key: "data-ownership-stewardship",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Ownership & Stewardship",
    nameAr: "ملكية البيانات والإشراف عليها",
    questionEn: "Who owns and who stewards each data object?",
    questionAr: "من يملك وينظر في كل كائن بيانات؟",
    icon: "person_check",
    path: "/reports/data-ownership",
    status: "available",
  },
  {
    key: "data-domain-landscape",
    domain: "data",
    kind: "list",
    level: "logical",
    nameEn: "Data Domain Landscape",
    nameAr: "مشهد مجال البيانات",
    questionEn: "What data objects exist and how are they organized?",
    questionAr: "ما هي كائنات البيانات الموجودة وكيف يتم تنظيمها؟",
    icon: "dashboard",
    path: "/reports/data-domain",
    status: "available",
  },
  {
    key: "data-classification-sensitivity",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Classification & Sensitivity",
    nameAr: "تصنيف البيانات والحساسية",
    questionEn: "Which data objects are classified as sensitive?",
    questionAr: "أي كائنات البيانات مصنفة كحساسة؟",
    icon: "security",
    path: "/reports/data-classification",
    status: "available",
  },
  {
    key: "application-data-crud",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Application-Data CRUD Matrix",
    nameAr: "مصفوفة CRUD للتطبيقات والبيانات",
    questionEn: "Which applications create, read, update, or delete which data?",
    questionAr: "أي التطبيقات تنشئ أو تقرأ أو تحدث أو تحذف أي بيانات؟",
    icon: "table_chart",
    path: "/reports/app-data-crud",
    status: "available",
  },
  {
    key: "data-object-relationships",
    domain: "data",
    kind: "diagram",
    level: "logical",
    nameEn: "Data Object Relationship Model",
    nameAr: "نموذج العلاقات بين كائنات البيانات",
    questionEn: "How are data objects related to each other?",
    questionAr: "كيف تترابط كائنات البيانات مع بعضها؟",
    icon: "hub",
    path: "/reports/data-relationships",
    status: "available",
  },
  {
    key: "data-entity-capability",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Entity / Business Capability",
    nameAr: "كيان البيانات / قدرة الأعمال",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "data-entity-applications",
    domain: "data",
    kind: "matrix",
    level: "logical",
    nameEn: "Data Entity / Applications",
    nameAr: "كيان البيانات / التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "data-vocabulary",
    domain: "data",
    kind: "list",
    level: "physical",
    nameEn: "Data Vocabulary",
    nameAr: "قاموس البيانات",
    status: "descoped",
  },
  {
    key: "data-vaults-catalog",
    domain: "data",
    kind: "list",
    level: "physical",
    nameEn: "Data Vaults Catalog",
    nameAr: "دليل مستودعات البيانات",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "data-entity-attributes",
    domain: "data",
    kind: "matrix",
    level: "physical",
    nameEn: "Data Entity / Data Attributes",
    nameAr: "كيان البيانات / عناصر البيانات",
    status: "descoped",
  },
  {
    key: "data-entity-vault",
    domain: "data",
    kind: "matrix",
    level: "physical",
    nameEn: "Data Entity / Data Vault",
    nameAr: "كيان البيانات / مستودع البيانات",
    path: "/reports/matrix",
    status: "available",
  },
  // ── Applications ────────────────────────────────────────────────────────
  {
    key: "applications-landscape",
    domain: "applications",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Applications Landscape",
    nameAr: "المشهد العام للتطبيقات",
    questionEn: "What applications does the enterprise operate?",
    questionAr: "ما هي التطبيقات التي تعمل بها المؤسسة؟",
    icon: "apps",
    path: "/layers/application",
    status: "available",
  },
  {
    key: "applications-catalog",
    domain: "applications",
    kind: "list",
    level: "logical",
    nameEn: "Applications Catalog",
    nameAr: "سجل التطبيقات",
    questionEn: "What is the complete inventory of applications?",
    questionAr: "ما هو السجل الكامل للتطبيقات؟",
    icon: "list",
    path: "/inventory?type=Application",
    status: "available",
  },
  {
    key: "application-beneficiary",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Beneficiary",
    nameAr: "التطبيق / المستفيد",
    status: "descoped",
  },
  {
    key: "application-org-unit",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Organizational Unit",
    nameAr: "التطبيق / الوحدة التنظيمية",
    questionEn: "Which applications serve which organizational units?",
    questionAr: "ما التطبيقات التي تخدم الوحدات التنظيمية؟",
    icon: "grid_view",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-service",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Business Service",
    nameAr: "التطبيق / خدمة الأعمال",
    questionEn: "Which applications deliver which business services?",
    questionAr: "ما التطبيقات التي تقدم خدمات الأعمال؟",
    icon: "grid_view",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-process",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Business Process",
    nameAr: "التطبيق / إجراء الأعمال",
    questionEn: "Which applications support which business processes?",
    questionAr: "ما التطبيقات التي تدعم عمليات الأعمال؟",
    icon: "grid_view",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "application-server",
    domain: "applications",
    kind: "matrix",
    level: "logical",
    nameEn: "Application / Server",
    nameAr: "التطبيق / الخادم",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "applications-by-org-unit",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Applications Viewpoint by Organizational Unit",
    nameAr: "منظور التطبيقات حسب الوحدة التنظيمية",
    path: "/reports/matrix",
    status: "planned",
  },
  {
    key: "application-modules-landscape",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Landscape of Application Modules",
    nameAr: "المشهد العام لوحدات التطبيقات",
    questionEn: "How are applications decomposed into modules?",
    questionAr: "كيف يتم تقسيم التطبيقات إلى وحدات؟",
    icon: "dashboard_customize",
    path: "/reports/application-modules",
    status: "available",
  },
  {
    key: "integration-landscape",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Integration Landscape",
    nameAr: "المشهد العام للتكامل",
    questionEn: "How do applications integrate and exchange data?",
    questionAr: "كيف تتكامل التطبيقات وتتبادل البيانات؟",
    icon: "hub",
    path: "/reports/interoperability",
    status: "available",
  },
  {
    key: "applications-integration",
    domain: "applications",
    kind: "diagram",
    level: "logical",
    nameEn: "Applications Integration Viewpoint",
    nameAr: "منظور تكامل التطبيقات",
    path: "/reports/dependencies",
    status: "available",
  },
  {
    key: "integration-point-register",
    domain: "applications",
    kind: "list",
    level: "physical",
    nameEn: "Technical Integration Point Register",
    nameAr: "سجل نقاط الربط التقني",
    path: "/inventory?type=Interface",
    status: "available",
  },
  {
    key: "application-security-software",
    domain: "applications",
    kind: "matrix",
    level: "physical",
    nameEn: "Application / Security Software",
    nameAr: "التطبيق / برمجيات الأمن",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "applications-by-development-type",
    domain: "applications",
    kind: "diagram",
    level: "physical",
    nameEn: "Applications by Development Type Showing Source Type",
    nameAr: "التطبيقات حسب نوع التطوير ونوع المصدر",
    path: "/reports/flexible-portfolio",
    status: "available",
  },
  // ── Technology ──────────────────────────────────────────────────────────
  {
    key: "datacenter-distribution",
    domain: "technology",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Datacenter Distribution",
    nameAr: "المشهد العام لتوزيع مراكز البيانات",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "technology-capabilities-landscape",
    domain: "technology",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Technology Architecture Capabilities",
    nameAr: "المشهد العام لقدرات بنية التقنية",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "infra-tools-catalog",
    domain: "technology",
    kind: "list",
    level: "logical",
    nameEn: "Infrastructure Tools Catalog",
    nameAr: "دليل أدوات البنية التحتية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "infra-services-catalog",
    domain: "technology",
    kind: "list",
    level: "logical",
    nameEn: "Infrastructure Services Catalog",
    nameAr: "دليل خدمات البنية التحتية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "datacenter-provider",
    domain: "technology",
    kind: "matrix",
    level: "logical",
    nameEn: "Datacenter / Service Provider",
    nameAr: "مركز البيانات / مزود الخدمة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "datacenter-application",
    domain: "technology",
    kind: "matrix",
    level: "logical",
    nameEn: "Datacenter / Application",
    nameAr: "مركز البيانات / التطبيق",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "network-architecture-landscape",
    domain: "technology",
    kind: "diagram",
    level: "logical",
    nameEn: "Network Architecture Landscape",
    nameAr: "المشهد العام لبنية الشبكة",
    path: "/reports/technology-landscape",
    status: "available",
  },
  {
    key: "physical-host-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Physical Host Hardware Catalog",
    nameAr: "دليل أجهزة المضيفات المادية",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "servers-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Servers Catalog",
    nameAr: "دليل الخوادم",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "network-devices-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Network Devices Catalog",
    nameAr: "دليل أجهزة الشبكة",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "storage-catalog",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Storage Catalog",
    nameAr: "دليل وحدات التخزين",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "network-connectivity-circuits",
    domain: "technology",
    kind: "diagram",
    level: "physical",
    nameEn: "Diagram of Network Connectivity Circuits",
    nameAr: "مخطط دوائر الربط الشبكي",
    status: "descoped",
  },
  // ── Phase 7: Technology Deployment & Cloud Views ────────────────────────
  {
    key: "technology-portfolio",
    domain: "technology",
    kind: "list",
    level: "physical",
    nameEn: "Technology Portfolio",
    nameAr: "محفظة التكنولوجيا",
    questionEn: "What technology assets are deployed and how are they characterized?",
    questionAr: "ما الأصول التكنولوجية المنتشرة وكيف تتسم؟",
    icon: "memory",
    path: "/reports/tech-portfolio",
    status: "available",
  },
  {
    key: "cloud-adoption",
    domain: "technology",
    kind: "diagram",
    level: "physical",
    nameEn: "Cloud Adoption View",
    nameAr: "عرض اعتماد السحابة",
    questionEn: "What is the organization's cloud migration and adoption rate?",
    questionAr: "ما معدل الهجرة واعتماد السحابة في المنظمة؟",
    icon: "cloud",
    path: "/reports/cloud-adoption",
    status: "available",
  },
  {
    key: "technology-stack",
    domain: "technology",
    kind: "diagram",
    level: "physical",
    nameEn: "Technology Stack View",
    nameAr: "عرض مكدس التكنولوجيا",
    questionEn: "How are technology components organized by architectural layer?",
    questionAr: "كيف يتم تنظيم مكونات التكنولوجيا حسب الطبقة المعمارية؟",
    icon: "architecture",
    path: "/reports/tech-stack",
    status: "available",
  },
  // ── Security ────────────────────────────────────────────────────────────
  {
    key: "security-service-provider",
    domain: "security",
    kind: "matrix",
    level: "conceptual",
    nameEn: "Security Service / Service Provider",
    nameAr: "خدمة الأمن / مزود الخدمة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-capabilities-landscape",
    domain: "security",
    kind: "diagram",
    level: "conceptual",
    nameEn: "Landscape of Security Architecture Capabilities",
    nameAr: "المشهد العام لقدرات بنية الأمن",
    path: "/layers/security",
    status: "available",
  },
  {
    key: "security-hardware-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Hardware Catalog",
    nameAr: "دليل أجهزة الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-software-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Software Catalog",
    nameAr: "دليل برمجيات الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-services-catalog",
    domain: "security",
    kind: "list",
    level: "logical",
    nameEn: "Security Services Catalog",
    nameAr: "دليل خدمات الأمن",
    path: "/inventory?type=ITComponent",
    status: "available",
  },
  {
    key: "security-function-locations",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Security Hardware & Software Function / Application Locations",
    nameAr: "وظائف أجهزة وبرمجيات الأمن / مواقع التطبيقات",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-functions-applications",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Security Hardware & Software Functions / Related Applications",
    nameAr: "وظائف أجهزة وبرمجيات الأمن / التطبيقات المرتبطة",
    path: "/reports/matrix",
    status: "available",
  },
  {
    key: "security-hardware-in-datacenters",
    domain: "security",
    kind: "diagram",
    level: "physical",
    nameEn: "Distribution of Security Hardware in Datacenters",
    nameAr: "توزيع أجهزة الأمن في مراكز البيانات",
    path: "/reports/technology-landscape",
    status: "available",
  },
  // ── Phase 8: Standards & Security Traceability ────────────────────────────
  {
    key: "security-controls-coverage",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Security Controls Coverage",
    nameAr: "تغطية مراقبات الأمن",
    questionEn: "What is the coverage of security controls across the portfolio?",
    questionAr: "ما تغطية مراقبات الأمن عبر المحفظة؟",
    icon: "security",
    path: "/reports/security-controls",
    status: "available",
  },
  {
    key: "standards-compliance-matrix",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Standards Compliance Matrix",
    nameAr: "مصفوفة الامتثال للمعايير",
    questionEn: "Which applications comply with architecture standards?",
    questionAr: "أي التطبيقات تمتثل لمعايير العمارة؟",
    icon: "checklist",
    path: "/reports/standards-matrix",
    status: "available",
  },
  {
    key: "principles-standards-traceability",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Principles & Standards Traceability",
    nameAr: "تتبع المبادئ والمعايير",
    questionEn: "How well do applications align with EA principles and standards?",
    questionAr: "ما مدى محاذاة التطبيقات مع مبادئ ومعايير العمارة؟",
    icon: "rule_folder",
    path: "/reports/principles-traceability",
    status: "available",
  },
  {
    key: "exception-waiver-matrix",
    domain: "security",
    kind: "matrix",
    level: "logical",
    nameEn: "Exception & Waiver Matrix",
    nameAr: "مصفوفة الاستثناءات والإعفاءات",
    questionEn: "What approved exceptions and waivers exist for architecture standards?",
    questionAr: "ما الاستثناءات والإعفاءات المعتمدة لمعايير العمارة؟",
    icon: "published_with_changes",
    path: "/reports/exceptions-waivers",
    status: "available",
  },
  // ── Phase 9: Beneficiary Experience Views ────────────────────────────
  {
    key: "persona-catalog",
    domain: "beneficiaryExperience",
    kind: "list",
    level: "conceptual",
    nameEn: "Persona Catalog",
    nameAr: "دليل الشخصيات",
    questionEn: "Who are the beneficiaries and what are their characteristics?",
    questionAr: "من هم المستفيدون وما هي خصائصهم؟",
    icon: "people",
    path: "/reports/personas",
    status: "available",
  },
  {
    key: "journey-map",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "logical",
    nameEn: "Journey Map",
    nameAr: "خريطة الرحلة",
    questionEn: "What do beneficiary journeys look like across stages and touchpoints?",
    questionAr: "كيف تبدو رحلات المستفيدين عبر المراحل ونقاط التلامس؟",
    icon: "journey",
    path: "/reports/journey-map",
    status: "available",
  },
  {
    key: "touchpoint-matrix",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Touchpoint Matrix",
    nameAr: "مصفوفة نقاط التلامس",
    questionEn: "Which personas use which channels and touchpoints?",
    questionAr: "أي الشخصيات تستخدم أي القنوات ونقاط التلامس؟",
    icon: "grid_view",
    path: "/reports/touchpoint-matrix",
    status: "available",
  },
  {
    key: "experience-heatmap",
    domain: "beneficiaryExperience",
    kind: "diagram",
    level: "logical",
    nameEn: "Experience Heatmap",
    nameAr: "خريطة الحرارة للتجربة",
    questionEn: "Where are satisfaction and pain points in the journey?",
    questionAr: "أين تقع نقاط الرضا والألم في الرحلة؟",
    icon: "heatmap",
    path: "/reports/experience-heatmap",
    status: "available",
  },
  {
    key: "beneficiary-landscape",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "physical",
    nameEn: "Beneficiary Landscape",
    nameAr: "مشهد المستفيدين",
    questionEn: "How are beneficiary groups distributed across organizational units?",
    questionAr: "كيف يتم توزيع مجموعات المستفيدين عبر الوحدات التنظيمية؟",
    icon: "public",
    path: "/reports/beneficiary-landscape",
    status: "available",
  },
  {
    key: "service-touchpoint-traceability",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "physical",
    nameEn: "Service Touchpoint Traceability",
    nameAr: "تتبع نقاط تلامس الخدمة",
    questionEn: "What channels and touchpoints deliver each government service?",
    questionAr: "ما القنوات ونقاط التلامس التي تقدم كل خدمة حكومية؟",
    icon: "connect_without_contact",
    path: "/reports/service-touchpoints",
    status: "available",
  },
  {
    key: "nea-viewpoints-dashboard",
    domain: "strategic",
    kind: "diagram",
    level: "conceptual",
    nameEn: "NEA Viewpoints Dashboard",
    nameAr: "لوحة معلومات وجهات النظر NEA",
    questionEn: "What is the complete reference of all 47 NEA viewpoints?",
    questionAr: "ما هو المرجع الشامل لجميع وجهات النظر 47 الوطنية للعمارة؟",
    icon: "dashboard",
    path: "/reports/nea-viewpoints",
    status: "available",
  },
  {
    key: "persona-beneficiary-mapping",
    domain: "beneficiaryExperience",
    kind: "matrix",
    level: "logical",
    nameEn: "Persona→Beneficiary Mapping",
    nameAr: "خريطة الشخصية→المستفيد",
    questionEn: "How do different beneficiary personas experience our services and journeys?",
    questionAr: "كيف تختبر شخصيات المستفيدين المختلفة خدماتنا ورحلاتنا؟",
    icon: "people",
    path: "/reports/persona-beneficiary-mapping",
    status: "available",
  },
];

export const NEA_DOMAIN_ORDER: NeaDomain[] = [
  "strategic",
  "business",
  "beneficiaryExperience",
  "data",
  "applications",
  "technology",
  "security",
];
