# Phase 2 card types to insert into TYPES array (before the final closing bracket)

{
    "key": "GovService",
    "label": "Government Service",
    "description": "Government services delivered to beneficiaries and other stakeholders.",
    "icon": "handshake",
    "color": "#00897b",
    "category": "Business",
    "has_hierarchy": True,
    "subtypes": [
        {
            "key": "publicService",
            "label": "Public Service",
            "translations": {
                "de": "Öffentlicher Dienst",
                "fr": "Service public",
                "es": "Servicio público",
                "it": "Servizio pubblico",
                "pt": "Serviço público",
                "zh": "公共服务",
                "ru": "Государственная служба",
                "da": "Offentlig service",
                "ar": "خدمة عامة",
            },
            "hidden_fields": [],
        },
        {
            "key": "businessService",
            "label": "Business Service",
            "translations": {
                "de": "Geschäftsservice",
                "fr": "Service métier",
                "es": "Servicio empresarial",
                "it": "Servizio aziendale",
                "pt": "Serviço de negócios",
                "zh": "业务服务",
                "ru": "Бизнес-услуга",
                "da": "Forretningsservice",
                "ar": "خدمة تجارية",
            },
            "hidden_fields": [],
        },
    ],
    "sort_order": 5,
    "fields_schema": [
        {
            "section": "Service Information",
            "translations": {
                "de": "Serviceinformationen",
                "fr": "Informations de service",
                "es": "Información del servicio",
                "it": "Informazioni sul servizio",
                "pt": "Informações do serviço",
                "zh": "服务信息",
                "ru": "Информация об услуге",
                "da": "Serviceoplysninger",
                "ar": "معلومات الخدمة",
            },
            "fields": [
                {
                    "key": "serviceCode",
                    "label": "Service Code",
                    "type": "text",
                    "weight": 1,
                    "translations": {
                        "de": "Servicecode",
                        "fr": "Code de service",
                        "es": "Código de servicio",
                        "it": "Codice servizio",
                        "pt": "Código de serviço",
                        "zh": "服务代码",
                        "ru": "Код услуги",
                        "da": "Servicekode",
                        "ar": "كود الخدمة",
                    },
                },
                {
                    "key": "serviceStatus",
                    "label": "Service Status",
                    "type": "single_select",
                    "options": [
                        {
                            "key": "active",
                            "label": "Active",
                            "color": "#4caf50",
                            "translations": {
                                "de": "Aktiv",
                                "fr": "Actif",
                                "es": "Activo",
                                "it": "Attivo",
                                "pt": "Ativo",
                                "zh": "活跃",
                                "ru": "Активный",
                                "da": "Aktiv",
                                "ar": "نشط",
                            },
                        },
                        {
                            "key": "inactive",
                            "label": "Inactive",
                            "color": "#9e9e9e",
                            "translations": {
                                "de": "Inaktiv",
                                "fr": "Inactif",
                                "es": "Inactivo",
                                "it": "Inattivo",
                                "pt": "Inativo",
                                "zh": "不活跃",
                                "ru": "Неактивный",
                                "da": "Inaktiv",
                                "ar": "غير نشط",
                            },
                        },
                    ],
                    "weight": 1,
                    "translations": {
                        "de": "Servicestatus",
                        "fr": "Statut du service",
                        "es": "Estado del servicio",
                        "it": "Stato del servizio",
                        "pt": "Status do serviço",
                        "zh": "服务状态",
                        "ru": "Статус услуги",
                        "da": "Servicestatus",
                        "ar": "حالة الخدمة",
                    },
                },
            ],
        },
    ],
},

{
    "key": "Beneficiary",
    "label": "Beneficiary",
    "description": "Individual users or groups receiving government services.",
    "icon": "group",
    "color": "#d81b60",
    "category": "Business",
    "has_hierarchy": False,
    "subtypes": [
        {
            "key": "citizen",
            "label": "Citizen",
            "translations": {
                "de": "Bürger",
                "fr": "Citoyen",
                "es": "Ciudadano",
                "it": "Cittadino",
                "pt": "Cidadão",
                "zh": "公民",
                "ru": "Гражданин",
                "da": "Borger",
                "ar": "مواطن",
            },
            "hidden_fields": [],
        },
        {
            "key": "business",
            "label": "Business",
            "translations": {
                "de": "Unternehmen",
                "fr": "Entreprise",
                "es": "Negocio",
                "it": "Azienda",
                "pt": "Negócio",
                "zh": "企业",
                "ru": "Бизнес",
                "da": "Virksomhed",
                "ar": "عمل",
            },
            "hidden_fields": [],
        },
        {
            "key": "government",
            "label": "Government",
            "translations": {
                "de": "Regierung",
                "fr": "Gouvernement",
                "es": "Gobierno",
                "it": "Governo",
                "pt": "Governo",
                "zh": "政府",
                "ru": "Правительство",
                "da": "Regering",
                "ar": "حكومة",
            },
            "hidden_fields": [],
        },
    ],
    "sort_order": 6,
    "fields_schema": [
        {
            "section": "Beneficiary Information",
            "translations": {
                "de": "Informationen zum Leistungsempfänger",
                "fr": "Informations sur le bénéficiaire",
                "es": "Información del beneficiario",
                "it": "Informazioni sul beneficiario",
                "pt": "Informações do beneficiário",
                "zh": "受益人信息",
                "ru": "Информация о получателе услуг",
                "da": "Modtagerinformationer",
                "ar": "معلومات المستفيد",
            },
            "fields": [],
        },
    ],
},

{
    "key": "BeneficiaryPersona",
    "label": "Beneficiary Persona",
    "description": "Archetypical beneficiary profiles with demographics, needs, and behaviors.",
    "icon": "person",
    "color": "#e91e63",
    "category": "Business",
    "has_hierarchy": False,
    "subtypes": [],
    "sort_order": 7,
    "fields_schema": [
        {
            "section": "Persona Details",
            "translations": {
                "de": "Persona-Details",
                "fr": "Détails de la persona",
                "es": "Detalles de la persona",
                "it": "Dettagli della persona",
                "pt": "Detalhes da persona",
                "zh": "角色详情",
                "ru": "Детали персоны",
                "da": "Persona-detaljer",
                "ar": "تفاصيل الشخصية",
            },
            "fields": [
                {
                    "key": "age",
                    "label": "Age Group",
                    "type": "text",
                    "weight": 1,
                    "translations": {
                        "de": "Altersgruppe",
                        "fr": "Groupe d'âge",
                        "es": "Grupo de edad",
                        "it": "Fascia d'età",
                        "pt": "Faixa etária",
                        "zh": "年龄组",
                        "ru": "Возрастная группа",
                        "da": "Aldersgruppe",
                        "ar": "فئة العمر",
                    },
                },
            ],
        },
    ],
},

{
    "key": "BeneficiaryJourney",
    "label": "Beneficiary Journey",
    "description": "End-to-end service experience paths including stages, touchpoints, and pain points.",
    "icon": "map",
    "color": "#f06292",
    "category": "Business",
    "has_hierarchy": True,
    "subtypes": [],
    "sort_order": 8,
    "fields_schema": [
        {
            "section": "Journey Details",
            "translations": {
                "de": "Reisedetails",
                "fr": "Détails du parcours",
                "es": "Detalles del viaje",
                "it": "Dettagli del percorso",
                "pt": "Detalhes da jornada",
                "zh": "旅程详情",
                "ru": "Детали путешествия",
                "da": "Rejsedetaljer",
                "ar": "تفاصيل الرحلة",
            },
            "fields": [],
        },
    ],
},

{
    "key": "ModelTemplate",
    "label": "Model/Template",
    "description": "Business process models, templates, and reference implementations.",
    "icon": "description",
    "color": "#5c6bc0",
    "category": "Business",
    "has_hierarchy": False,
    "subtypes": [
        {
            "key": "processModel",
            "label": "Process Model",
            "translations": {
                "de": "Prozessmodell",
                "fr": "Modèle de processus",
                "es": "Modelo de proceso",
                "it": "Modello di processo",
                "pt": "Modelo de processo",
                "zh": "流程模型",
                "ru": "Модель процесса",
                "da": "Procesmodel",
                "ar": "نموذج العملية",
            },
            "hidden_fields": [],
        },
        {
            "key": "template",
            "label": "Template",
            "translations": {
                "de": "Vorlage",
                "fr": "Modèle",
                "es": "Plantilla",
                "it": "Modello",
                "pt": "Modelo",
                "zh": "模板",
                "ru": "Шаблон",
                "da": "Skabelon",
                "ar": "قالب",
            },
            "hidden_fields": [],
        },
    ],
    "sort_order": 9,
    "fields_schema": [
        {
            "section": "Model Information",
            "translations": {
                "de": "Modellinformationen",
                "fr": "Informations du modèle",
                "es": "Información del modelo",
                "it": "Informazioni del modello",
                "pt": "Informações do modelo",
                "zh": "模型信息",
                "ru": "Информация о модели",
                "da": "Modeloplysninger",
                "ar": "معلومات النموذج",
            },
            "fields": [],
        },
    ],
},

{
    "key": "Policy",
    "label": "Policy",
    "description": "Business policies, regulations, and governance rules.",
    "icon": "gavel",
    "color": "#7986cb",
    "category": "Business",
    "has_hierarchy": False,
    "subtypes": [
        {
            "key": "businessPolicy",
            "label": "Business Policy",
            "translations": {
                "de": "Geschäftspolitik",
                "fr": "Politique métier",
                "es": "Política empresarial",
                "it": "Politica aziendale",
                "pt": "Política de negócios",
                "zh": "业务政策",
                "ru": "Деловая политика",
                "da": "Forretningspolitik",
                "ar": "سياسة الأعمال",
            },
            "hidden_fields": [],
        },
        {
            "key": "regulation",
            "label": "Regulation",
            "translations": {
                "de": "Regelung",
                "fr": "Réglementation",
                "es": "Regulación",
                "it": "Regolamento",
                "pt": "Regulação",
                "zh": "规制",
                "ru": "Нормативно-правовой акт",
                "da": "Regulering",
                "ar": "لائحة",
            },
            "hidden_fields": [],
        },
    ],
    "sort_order": 10,
    "fields_schema": [
        {
            "section": "Policy Information",
            "translations": {
                "de": "Richtlieninformationen",
                "fr": "Informations sur la politique",
                "es": "Información de la política",
                "it": "Informazioni sulla politica",
                "pt": "Informações de política",
                "zh": "政策信息",
                "ru": "Информация о политике",
                "da": "Politikinformationer",
                "ar": "معلومات السياسة",
            },
            "fields": [],
        },
    ],
},

{
    "key": "Position",
    "label": "Position",
    "description": "Organizational roles, positions, and job titles.",
    "icon": "badge",
    "color": "#29b6f6",
    "category": "Business",
    "has_hierarchy": False,
    "subtypes": [
        {
            "key": "executive",
            "label": "Executive",
            "translations": {
                "de": "Führungskraft",
                "fr": "Cadre",
                "es": "Ejecutivo",
                "it": "Dirigente",
                "pt": "Executivo",
                "zh": "高管",
                "ru": "Руководитель",
                "da": "Direktør",
                "ar": "تنفيذي",
            },
            "hidden_fields": [],
        },
        {
            "key": "manager",
            "label": "Manager",
            "translations": {
                "de": "Manager",
                "fr": "Gestionnaire",
                "es": "Gerente",
                "it": "Direttore",
                "pt": "Gerente",
                "zh": "经理",
                "ru": "Менеджер",
                "da": "Leder",
                "ar": "مدير",
            },
            "hidden_fields": [],
        },
        {
            "key": "specialist",
            "label": "Specialist",
            "translations": {
                "de": "Spezialist",
                "fr": "Spécialiste",
                "es": "Especialista",
                "it": "Specialista",
                "pt": "Especialista",
                "zh": "专家",
                "ru": "Специалист",
                "da": "Specialist",
                "ar": "متخصص",
            },
            "hidden_fields": [],
        },
    ],
    "sort_order": 11,
    "fields_schema": [
        {
            "section": "Position Information",
            "translations": {
                "de": "Positionsinformationen",
                "fr": "Informations de poste",
                "es": "Información de puesto",
                "it": "Informazioni posizione",
                "pt": "Informações de cargo",
                "zh": "职位信息",
                "ru": "Информация о должности",
                "da": "Stillingsinformationer",
                "ar": "معلومات المنصب",
            },
            "fields": [],
        },
    ],
},
